# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.


SHELL = /bin/sh

srcdir = .
top_srcdir = ../..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/irssi
pkglibdir = $(libdir)/irssi
pkgincludedir = $(includedir)/irssi

top_builddir = ../..

ACLOCAL = /Users/kolis/Projects/MacIrssi/irssi-0.8.9/missing aclocal-1.4
AUTOCONF = autoconf
AUTOMAKE = /Users/kolis/Projects/MacIrssi/irssi-0.8.9/missing automake-1.4
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = 
host_triplet = powerpc-apple-darwin8.2.0
AR = ar
AS = @AS@
CC = gcc
CHAT_MODULES = irc
COMMON_LIBS = ../fe-common/irc/libfe_common_irc.a ../fe-common/irc/dcc/libfe_irc_dcc.a ../fe-common/irc/notifylist/libfe_irc_notifylist.a ../fe-common/core/libfe_common_core.a  ../irc/libirc.a ../irc/core/libirc_core.a ../irc/dcc/libirc_dcc.a ../irc/flood/libirc_flood.a ../irc/notifylist/libirc_notifylist.a ../core/libcore.a ../lib-config/libirssi_config.a ../lib-popt/libpopt.a
COMMON_NOUI_LIBS =  ../irc/libirc.a ../irc/core/libirc_core.a ../irc/dcc/libirc_dcc.a ../irc/flood/libirc_flood.a ../irc/notifylist/libirc_notifylist.a ../core/libcore.a ../lib-config/libirssi_config.a ../lib-popt/libpopt.a
CPP = gcc -E
CURSES_INCLUDEDIR = 
CURSES_LIBS = 
CXX = g++
CXXCPP = g++ -E
DLLTOOL = @DLLTOOL@
DYNALOADER_A = 
ECHO = echo
EGREP = grep -E
EXEEXT = 
F77 = 
GCJ = @GCJ@
GCJFLAGS = @GCJFLAGS@
GLIB_CFLAGS = -I/sw/include/glib-2.0 -I/sw/lib/glib-2.0/include  
GLIB_CONFIG = 
GLIB_GENMARSHAL = glib-genmarshal
GLIB_LIBS = -L/sw/lib -lgmodule-2.0 -lglib-2.0 -lintl -liconv  
GLIB_MKENUMS = glib-mkenums
GOBJECT_QUERY = gobject-query
LIBPERL_A = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = #
MAKEINFO = makeinfo
OBJDUMP = @OBJDUMP@
OBJEXT = o
PACKAGE = irssi
PERL_CFLAGS = -g -pipe -fno-common -DPERL_DARWIN -no-cpp-precomp -fno-strict-aliasing -I/usr/local/include -I/System/Library/Perl/5.8.6/darwin-thread-multi-2level/CORE
PERL_EXTRA_OPTS = CCCDLFLAGS="-fPIC"
PERL_FE_LINK_LIBS = ../perl/libfe_perl_static.la
PERL_LDFLAGS = 
PERL_LIBTOOL = $(SHELL) $(top_builddir)/libtool
PERL_LINK_FLAGS = -L/usr/local/lib /System/Library/Perl/5.8.6/darwin-thread-multi-2level/auto/DynaLoader/DynaLoader.a -L/System/Library/Perl/5.8.6/darwin-thread-multi-2level/CORE -lperl -ldl -lm
PERL_LINK_LIBS = ../perl/libperl_core_static.la
PERL_MM_PARAMS = 
PERL_STATIC_LIBS = 0
PERL_USE_LIB = 
PKG_CONFIG = /sw/bin/pkg-config
PROG_LIBS =  -L/sw/lib -lgmodule-2.0 -lglib-2.0 -lintl -liconv   -lssl -lcrypto
RANLIB = ranlib
RC = @RC@
SSL_LIBS = -lssl -lcrypto
STRIP = strip
TEXTUI_LIBS = 
VERSION = 0.8.9
VERSION_DATE = 20031210
VERSION_TIME = 2316
irc_MODULES = dcc flood notifylist
perl_module_fe_lib = 
perl_module_lib = 
perl_static_fe_lib = libfe_perl_static.la
perl_static_lib = libperl_core_static.la
perlpath = /usr/bin/perl
sedpath = /usr/bin/sed

bin_PROGRAMS = irssi

INCLUDES =  	-I$(top_srcdir)/src 	-I$(top_srcdir)/src/core/ 	-I$(top_srcdir)/src/fe-common/core/ 	$(GLIB_CFLAGS) 	$(CURSES_INCLUDEDIR) 	-DLOCALEDIR=\""$(datadir)/locale"\"


irssi_DEPENDENCIES =  	../fe-common/irc/libfe_common_irc.a ../fe-common/irc/dcc/libfe_irc_dcc.a ../fe-common/irc/notifylist/libfe_irc_notifylist.a ../fe-common/core/libfe_common_core.a  ../irc/libirc.a ../irc/core/libirc_core.a ../irc/dcc/libirc_dcc.a ../irc/flood/libirc_flood.a ../irc/notifylist/libirc_notifylist.a ../core/libcore.a ../lib-config/libirssi_config.a ../lib-popt/libpopt.a 	../perl/libperl_core_static.la 	../perl/libfe_perl_static.la


irssi_LDFLAGS = -export-dynamic

irssi_LDADD =  	../fe-common/irc/libfe_common_irc.a ../fe-common/irc/dcc/libfe_irc_dcc.a ../fe-common/irc/notifylist/libfe_irc_notifylist.a ../fe-common/core/libfe_common_core.a  ../irc/libirc.a ../irc/core/libirc_core.a ../irc/dcc/libirc_dcc.a ../irc/flood/libirc_flood.a ../irc/notifylist/libirc_notifylist.a ../core/libcore.a ../lib-config/libirssi_config.a ../lib-popt/libpopt.a 	../perl/libperl_core_static.la 	../perl/libfe_perl_static.la 	-L/usr/local/lib /System/Library/Perl/5.8.6/darwin-thread-multi-2level/auto/DynaLoader/DynaLoader.a -L/System/Library/Perl/5.8.6/darwin-thread-multi-2level/CORE -lperl -ldl -lm 	 -L/sw/lib -lgmodule-2.0 -lglib-2.0 -lintl -liconv   -lssl -lcrypto 	


tparm_sources =  	tparm.c


terminfo_sources =          term-terminfo.c         terminfo-core.c


curses_sources =  	term-curses.c


#use_tparm_sources = $(tparm_sources)
#use_term_sources = $(curses_sources)
use_term_sources = $(terminfo_sources)

irssi_SOURCES =          gui-entry.c 	gui-expandos.c         gui-printtext.c         gui-readline.c         gui-windows.c 	lastlog.c         mainwindows.c         mainwindow-activity.c         mainwindows-layout.c         statusbar.c         statusbar-config.c         statusbar-items.c         term.c 	term-dummy.c 	$(use_tparm_sources) 	$(use_term_sources)         textbuffer.c         textbuffer-commands.c         textbuffer-reformat.c         textbuffer-view.c 	utf8.c         irssi.c 	module-formats.c


noinst_HEADERS =          gui-entry.h         gui-printtext.h         gui-readline.h         gui-windows.h         mainwindows.h         statusbar.h         statusbar-config.h 	term.h 	terminfo-core.h         textbuffer.h         textbuffer-view.h         textbuffer-reformat.h 	utf8.h 	module.h 	module-formats.h


EXTRA_DIST =  	$(tparm_sources) 	$(terminfo_sources) 	$(curses_sources)

mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../../config.h
CONFIG_CLEAN_FILES = 
bin_PROGRAMS =  irssi$(EXEEXT)
PROGRAMS =  $(bin_PROGRAMS)


DEFS = -DHAVE_CONFIG_H -I. -I$(srcdir) -I../..
CPPFLAGS = 
LDFLAGS = 
LIBS = 
##irssi_OBJECTS =  gui-entry.$(OBJEXT) \
##gui-expandos.$(OBJEXT) \
##gui-printtext.$(OBJEXT) \
##gui-readline.$(OBJEXT) \
##gui-windows.$(OBJEXT) \
##lastlog.$(OBJEXT) \
##mainwindows.$(OBJEXT) \
##mainwindow-activity.$(OBJEXT) \
##mainwindows-layout.$(OBJEXT) \
##statusbar.$(OBJEXT) \
##statusbar-config.$(OBJEXT) \
##statusbar-items.$(OBJEXT) \
##term.$(OBJEXT) term-dummy.$(OBJEXT) \
##tparm.$(OBJEXT) term-curses.$(OBJEXT) \
##textbuffer.$(OBJEXT) \
##textbuffer-commands.$(OBJEXT) \
##textbuffer-reformat.$(OBJEXT) \
##textbuffer-view.$(OBJEXT) \
##utf8.$(OBJEXT) irssi.$(OBJEXT) \
##module-formats.$(OBJEXT)
irssi_OBJECTS =  gui-entry.$(OBJEXT) \
gui-expandos.$(OBJEXT) \
gui-printtext.$(OBJEXT) \
gui-readline.$(OBJEXT) \
gui-windows.$(OBJEXT) \
lastlog.$(OBJEXT) \
mainwindows.$(OBJEXT) \
mainwindow-activity.$(OBJEXT) \
mainwindows-layout.$(OBJEXT) \
statusbar.$(OBJEXT) \
statusbar-config.$(OBJEXT) \
statusbar-items.$(OBJEXT) \
term.$(OBJEXT) term-dummy.$(OBJEXT) \
term-terminfo.$(OBJEXT) \
terminfo-core.$(OBJEXT) \
textbuffer.$(OBJEXT) \
textbuffer-commands.$(OBJEXT) \
textbuffer-reformat.$(OBJEXT) \
textbuffer-view.$(OBJEXT) \
utf8.$(OBJEXT) irssi.$(OBJEXT) \
module-formats.$(OBJEXT)
#irssi_OBJECTS =  gui-entry.$(OBJEXT) \
#gui-expandos.$(OBJEXT) \
#gui-printtext.$(OBJEXT) \
#gui-readline.$(OBJEXT) \
#gui-windows.$(OBJEXT) \
#lastlog.$(OBJEXT) \
#mainwindows.$(OBJEXT) \
#mainwindow-activity.$(OBJEXT) \
#mainwindows-layout.$(OBJEXT) \
#statusbar.$(OBJEXT) \
#statusbar-config.$(OBJEXT) \
#statusbar-items.$(OBJEXT) \
#term.$(OBJEXT) term-dummy.$(OBJEXT) \
#tparm.$(OBJEXT) \
#term-terminfo.$(OBJEXT) \
#terminfo-core.$(OBJEXT) \
#textbuffer.$(OBJEXT) \
#textbuffer-commands.$(OBJEXT) \
#textbuffer-reformat.$(OBJEXT) \
#textbuffer-view.$(OBJEXT) \
#utf8.$(OBJEXT) irssi.$(OBJEXT) \
#module-formats.$(OBJEXT)
#irssi_OBJECTS =  gui-entry.$(OBJEXT) \
#gui-expandos.$(OBJEXT) \
#gui-printtext.$(OBJEXT) \
#gui-readline.$(OBJEXT) \
#gui-windows.$(OBJEXT) \
#lastlog.$(OBJEXT) \
#mainwindows.$(OBJEXT) \
#mainwindow-activity.$(OBJEXT) \
#mainwindows-layout.$(OBJEXT) \
#statusbar.$(OBJEXT) \
#statusbar-config.$(OBJEXT) \
#statusbar-items.$(OBJEXT) \
#term.$(OBJEXT) term-dummy.$(OBJEXT) \
#term-curses.$(OBJEXT) \
#textbuffer.$(OBJEXT) \
#textbuffer-commands.$(OBJEXT) \
#textbuffer-reformat.$(OBJEXT) \
#textbuffer-view.$(OBJEXT) \
#utf8.$(OBJEXT) irssi.$(OBJEXT) \
#module-formats.$(OBJEXT)
CFLAGS = -g -O2 -Wall
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
HEADERS =  $(noinst_HEADERS)

DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
SOURCES = $(irssi_SOURCES)
OBJECTS = $(irssi_OBJECTS)

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .lo .o .obj .s
$(srcdir)/Makefile.in: # Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps src/fe-text/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo " $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	    $(LIBTOOL)  --mode=install $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(bin_PROGRAMS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

.c.o:
	$(COMPILE) -c $<

# FIXME: We should only use cygpath when building on Windows,
# and only if it is available.
.c.obj:
	$(COMPILE) -c `cygpath -w $<`

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core
	-rm -f *.$(OBJEXT)

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

.c.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.s.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

.S.lo:
	$(LIBTOOL) --mode=compile $(COMPILE) -c $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:

maintainer-clean-libtool:

irssi$(EXEEXT): $(irssi_OBJECTS) $(irssi_DEPENDENCIES)
	@rm -f irssi$(EXEEXT)
	$(LINK) $(irssi_LDFLAGS) $(irssi_OBJECTS) $(irssi_LDADD) $(LIBS)

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags -o $$here/TAGS $(ETAGS_ARGS) $$tags  $$unique $(LISP))

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = src/fe-text

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-binPROGRAMS
install-exec: install-exec-am

install-data-am:
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-binPROGRAMS
uninstall: uninstall-am
all-am: Makefile $(PROGRAMS) $(HEADERS)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(bindir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-binPROGRAMS mostlyclean-compile \
		mostlyclean-libtool mostlyclean-tags \
		mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-binPROGRAMS clean-compile clean-libtool clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-binPROGRAMS distclean-compile distclean-libtool \
		distclean-tags distclean-generic clean-am
	-rm -f libtool

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-binPROGRAMS \
		maintainer-clean-compile maintainer-clean-libtool \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-binPROGRAMS distclean-binPROGRAMS clean-binPROGRAMS \
maintainer-clean-binPROGRAMS uninstall-binPROGRAMS install-binPROGRAMS \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile mostlyclean-libtool distclean-libtool \
clean-libtool maintainer-clean-libtool tags mostlyclean-tags \
distclean-tags clean-tags maintainer-clean-tags distdir info-am info \
dvi-am dvi check check-am installcheck-am installcheck install-exec-am \
install-exec install-data-am install-data install-am install \
uninstall-am uninstall all-redirect all-am all installdirs \
mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
