/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Channel.xs. Do not edit this file, edit Channel.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Channel.xs"
#include "module.h"

#line 13 "Channel.c"

XS(XS_Irssi__Irc_get_mask); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_get_mask)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::get_mask(nick, address, flags)");
    {
	char *	nick = (char *)SvPV_nolen(ST(0));
	char *	address = (char *)SvPV_nolen(ST(1));
	int	flags = (int)SvIV(ST(2));
	char *	RETVAL;
	dXSTARG;

	RETVAL = irc_get_mask(nick, address, flags);
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_MASK_NICK); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_MASK_NICK)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::MASK_NICK()");
    {
	int	RETVAL;
	dXSTARG;
#line 15 "Channel.xs"
	RETVAL = IRC_MASK_NICK;
#line 46 "Channel.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_MASK_USER); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_MASK_USER)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::MASK_USER()");
    {
	int	RETVAL;
	dXSTARG;
#line 22 "Channel.xs"
	RETVAL = IRC_MASK_USER;
#line 64 "Channel.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_MASK_HOST); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_MASK_HOST)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::MASK_HOST()");
    {
	int	RETVAL;
	dXSTARG;
#line 29 "Channel.xs"
	RETVAL = IRC_MASK_HOST;
#line 82 "Channel.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_MASK_DOMAIN); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_MASK_DOMAIN)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::MASK_DOMAIN()");
    {
	int	RETVAL;
	dXSTARG;
#line 36 "Channel.xs"
	RETVAL = IRC_MASK_DOMAIN;
#line 100 "Channel.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc__Channel_bans); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Channel_bans)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Channel::bans(channel)");
    SP -= items;
    {
	Irssi__Irc__Channel	channel = irssi_ref_object(ST(0));
#line 46 "Channel.xs"
	GSList *tmp;
#line 118 "Channel.c"
#line 48 "Channel.xs"
	for (tmp = channel->banlist; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::Irc::Ban")));
	}
#line 123 "Channel.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Irc__Channel_nick_insert); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Channel_nick_insert)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Channel::nick_insert(channel, nick, op, halfop, voice, send_massjoin)");
    {
	Irssi__Irc__Channel	channel = irssi_ref_object(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	int	op = (int)SvIV(ST(2));
	int	halfop = (int)SvIV(ST(3));
	int	voice = (int)SvIV(ST(4));
	int	send_massjoin = (int)SvIV(ST(5));
	Irssi__Irc__Nick	RETVAL;
#line 61 "Channel.xs"
	RETVAL = irc_nicklist_insert(channel, nick, op, halfop, voice, send_massjoin);
#line 146 "Channel.c"
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Irc__Channel); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Irc__Channel)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::Irc::get_mask", XS_Irssi__Irc_get_mask, file, "$$$");
        newXSproto("Irssi::Irc::MASK_NICK", XS_Irssi__Irc_MASK_NICK, file, "");
        newXSproto("Irssi::Irc::MASK_USER", XS_Irssi__Irc_MASK_USER, file, "");
        newXSproto("Irssi::Irc::MASK_HOST", XS_Irssi__Irc_MASK_HOST, file, "");
        newXSproto("Irssi::Irc::MASK_DOMAIN", XS_Irssi__Irc_MASK_DOMAIN, file, "");
        newXSproto("Irssi::Irc::Channel::bans", XS_Irssi__Irc__Channel_bans, file, "$");
        newXSproto("Irssi::Irc::Channel::nick_insert", XS_Irssi__Irc__Channel_nick_insert, file, "$$$$$$");
    XSRETURN_YES;
}

