/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Ctcp.xs. Do not edit this file, edit Ctcp.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Ctcp.xs"
#include "module.h"
#include "ctcp.h"

#line 14 "Ctcp.c"

XS(XS_Irssi_ctcp_register); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_ctcp_register)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::ctcp_register(name)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));

	ctcp_register(name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_ctcp_unregister); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_ctcp_unregister)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::ctcp_unregister(name)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));

	ctcp_unregister(name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc__Server_ctcp_send_reply); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_ctcp_send_reply)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::ctcp_send_reply(server, data)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	data = (char *)SvPV_nolen(ST(1));

	ctcp_send_reply(server, data);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Irc__Ctcp); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Irc__Ctcp)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::ctcp_register", XS_Irssi_ctcp_register, file, "$");
        newXSproto("Irssi::ctcp_unregister", XS_Irssi_ctcp_unregister, file, "$");
        newXSproto("Irssi::Irc::Server::ctcp_send_reply", XS_Irssi__Irc__Server_ctcp_send_reply, file, "$$");
    XSRETURN_YES;
}

