/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Dcc.xs. Do not edit this file, edit Dcc.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Dcc.xs"
#include "module.h"

#line 13 "Dcc.c"

XS(XS_Irssi__Irc_dccs); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dccs)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::dccs()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 9 "Dcc.xs"
	GSList *tmp;
#line 26 "Dcc.c"
#line 11 "Dcc.xs"
	for (tmp = dcc_conns; tmp != NULL; tmp = tmp->next) 
		XPUSHs(sv_2mortal(simple_iobject_bless((DCC_REC *) tmp->data)));
#line 30 "Dcc.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Irc_dcc_register_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_register_type)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::dcc_register_type(type)");
    {
	char *	type = (char *)SvPV_nolen(ST(0));

	dcc_register_type(type);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc_dcc_unregister_type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_unregister_type)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::dcc_unregister_type(type)");
    {
	char *	type = (char *)SvPV_nolen(ST(0));

	dcc_unregister_type(type);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc_dcc_str2type); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_str2type)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::dcc_str2type(str)");
    {
	char *	str = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = dcc_str2type(str);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_dcc_type2str); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_type2str)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::dcc_type2str(type)");
    {
	int	type = (int)SvIV(ST(0));
	char *	RETVAL;
	dXSTARG;
#line 30 "Dcc.xs"
	RETVAL = (char *) module_find_id_str("DCC", type);
#line 97 "Dcc.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_dcc_find_request_latest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_find_request_latest)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::dcc_find_request_latest(type)");
    {
	int	type = (int)SvIV(ST(0));
	Irssi__Irc__Dcc	RETVAL;

	RETVAL = dcc_find_request_latest(type);
	ST(0) = simple_iobject_bless((DCC_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_dcc_find_request); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_find_request)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::dcc_find_request(type, nick, arg)");
    {
	int	type = (int)SvIV(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	char *	arg = (char *)SvPV_nolen(ST(2));
	Irssi__Irc__Dcc	RETVAL;

	RETVAL = dcc_find_request(type, nick, arg);
	ST(0) = simple_iobject_bless((DCC_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_dcc_chat_find_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_chat_find_id)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::dcc_chat_find_id(id)");
    {
	char *	id = (char *)SvPV_nolen(ST(0));
	Irssi__Irc__Dcc__Chat	RETVAL;

	RETVAL = dcc_chat_find_id(id);
	ST(0) = simple_iobject_bless((DCC_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc_dcc_chat_send); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_chat_send)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::dcc_chat_send(dcc, data)");
    {
	Irssi__Irc__Dcc__Chat	dcc = irssi_ref_object(ST(0));
	char *	data = (char *)SvPV_nolen(ST(1));

	dcc_chat_send(dcc, data);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc_dcc_ctcp_message); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_ctcp_message)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::dcc_ctcp_message(server, target, chat, notice, msg)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	target = (char *)SvPV_nolen(ST(1));
	Irssi__Irc__Dcc__Chat	chat = irssi_ref_object(ST(2));
	int	notice = (int)SvIV(ST(3));
	char *	msg = (char *)SvPV_nolen(ST(4));

	dcc_ctcp_message(server, target, chat, notice, msg);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc_dcc_get_download_path); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_dcc_get_download_path)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::dcc_get_download_path(fname)");
    SP -= items;
    {
	char *	fname = (char *)SvPV_nolen(ST(0));
#line 65 "Dcc.xs"
	char *ret;
#line 209 "Dcc.c"
#line 67 "Dcc.xs"
	ret = dcc_get_download_path(fname);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free(ret);
#line 214 "Dcc.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Irc__Dcc_init_rec); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Dcc_init_rec)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Dcc::init_rec(dcc, server, chat, nick, arg)");
    {
	Irssi__Irc__Dcc	dcc = irssi_ref_object(ST(0));
	Irssi__Irc__Server	server = irssi_ref_object(ST(1));
	Irssi__Irc__Dcc__Chat	chat = irssi_ref_object(ST(2));
	char *	nick = (char *)SvPV_nolen(ST(3));
	char *	arg = (char *)SvPV_nolen(ST(4));

	dcc_init_rec(dcc, server, chat, nick, arg);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc__Dcc_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Dcc_destroy)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Dcc::destroy(dcc)");
    {
	Irssi__Irc__Dcc	dcc = irssi_ref_object(ST(0));

	dcc_destroy(dcc);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc__Dcc_close); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Dcc_close)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Dcc::close(dcc)");
    {
	Irssi__Irc__Dcc	dcc = irssi_ref_object(ST(0));

	dcc_close(dcc);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Irc__Dcc_reject); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Dcc_reject)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Dcc::reject(dcc, server)");
    {
	Irssi__Irc__Dcc	dcc = irssi_ref_object(ST(0));
	Irssi__Irc__Server	server = irssi_ref_object(ST(1));

	dcc_reject(dcc, server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Windowitem_get_dcc); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_get_dcc)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Windowitem::get_dcc(item)");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	Irssi__Irc__Dcc__Chat	RETVAL;

	RETVAL = item_get_dcc(item);
	ST(0) = simple_iobject_bless((DCC_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Irc__Dcc); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Irc__Dcc)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::Irc::dccs", XS_Irssi__Irc_dccs, file, "");
        newXSproto("Irssi::Irc::dcc_register_type", XS_Irssi__Irc_dcc_register_type, file, "$");
        newXSproto("Irssi::Irc::dcc_unregister_type", XS_Irssi__Irc_dcc_unregister_type, file, "$");
        newXSproto("Irssi::Irc::dcc_str2type", XS_Irssi__Irc_dcc_str2type, file, "$");
        newXSproto("Irssi::Irc::dcc_type2str", XS_Irssi__Irc_dcc_type2str, file, "$");
        newXSproto("Irssi::Irc::dcc_find_request_latest", XS_Irssi__Irc_dcc_find_request_latest, file, "$");
        newXSproto("Irssi::Irc::dcc_find_request", XS_Irssi__Irc_dcc_find_request, file, "$$$");
        newXSproto("Irssi::Irc::dcc_chat_find_id", XS_Irssi__Irc_dcc_chat_find_id, file, "$");
        newXSproto("Irssi::Irc::dcc_chat_send", XS_Irssi__Irc_dcc_chat_send, file, "$$");
        newXSproto("Irssi::Irc::dcc_ctcp_message", XS_Irssi__Irc_dcc_ctcp_message, file, "$$$$$");
        newXSproto("Irssi::Irc::dcc_get_download_path", XS_Irssi__Irc_dcc_get_download_path, file, "$");
        newXSproto("Irssi::Irc::Dcc::init_rec", XS_Irssi__Irc__Dcc_init_rec, file, "$$$$$");
        newXSproto("Irssi::Irc::Dcc::destroy", XS_Irssi__Irc__Dcc_destroy, file, "$");
        newXSproto("Irssi::Irc::Dcc::close", XS_Irssi__Irc__Dcc_close, file, "$");
        newXSproto("Irssi::Irc::Dcc::reject", XS_Irssi__Irc__Dcc_reject, file, "$$");
        newXSproto("Irssi::Windowitem::get_dcc", XS_Irssi__Windowitem_get_dcc, file, "$");
    XSRETURN_YES;
}

