/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Netsplit.xs. Do not edit this file, edit Netsplit.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Netsplit.xs"
#include "module.h"

#line 13 "Netsplit.c"

XS(XS_Irssi__Irc__Server_netsplit_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_netsplit_find)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::netsplit_find(server, nick, address)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	char *	address = (char *)SvPV_nolen(ST(2));
	Irssi__Irc__Netsplit	RETVAL;

	RETVAL = netsplit_find(server, nick, address);
	ST(0) = plain_bless(RETVAL, "Irssi::Irc::Netsplit");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Irc__Server_netsplit_find_channel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_netsplit_find_channel)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::netsplit_find_channel(server, nick, address, channel)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	char *	address = (char *)SvPV_nolen(ST(2));
	char *	channel = (char *)SvPV_nolen(ST(3));
	Irssi__Irc__Netsplitchannel	RETVAL;

	RETVAL = netsplit_find_channel(server, nick, address, channel);
	ST(0) = plain_bless(RETVAL, "Irssi::Irc::Netsplitchannel");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Irc__Netsplit); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Irc__Netsplit)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::Irc::Server::netsplit_find", XS_Irssi__Irc__Server_netsplit_find, file, "$$$");
        newXSproto("Irssi::Irc::Server::netsplit_find_channel", XS_Irssi__Irc__Server_netsplit_find_channel, file, "$$$$");
    XSRETURN_YES;
}

