/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Query.xs. Do not edit this file, edit Query.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Query.xs"
#include "module.h"

#line 13 "Query.c"

XS(XS_Irssi__Irc__Server_query_create); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_query_create)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::query_create(server_tag, nick, automatic)");
    {
	char *	server_tag = (char *)SvPV_nolen(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	int	automatic = (int)SvIV(ST(2));
	Irssi__Irc__Query	RETVAL;

	RETVAL = irc_query_create(server_tag, nick, automatic);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Irc__Query); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Irc__Query)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::Irc::Server::query_create", XS_Irssi__Irc__Server_query_create, file, "$$$");
    XSRETURN_YES;
}

