/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Core.xs. Do not edit this file, edit Core.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Core.xs"
#include "module.h"
#include "irssi-version.h"
#include "core.h"

#include "pidwait.h"
#include "session.h"

#define DEFAULT_COMMAND_CATEGORY "Perl scripts' commands"

void perl_signal_add_hash(int priority, SV *sv)
{
	HV *hv;
        HE *he;
	I32 len;

	if (!is_hvref(sv))
		croak("Usage: Irssi::signal_add(hash)");

        hv = hvref(sv);
	hv_iterinit(hv);
	while ((he = hv_iternext(hv)) != NULL)
                perl_signal_add_full(hv_iterkey(he, &len), HeVAL(he), priority);
}

static void perl_command_bind_add_hash(int priority, SV *sv, char *category)
{
	HV *hv;
        HE *he;
	I32 len;

        hv = hvref(sv);
	hv_iterinit(hv);
	while ((he = hv_iternext(hv)) != NULL)
		perl_command_bind_to(hv_iterkey(he, &len), category, HeVAL(he), priority);
}

static void handle_command_bind(int priority, int items, SV *p0, SV *p1, SV *p2)
{
	char *category;
	int hash;

	hash = items > 0 && is_hvref(p0);
	if (!hash) {
		if (items < 2 || items > 3)
			croak("Usage: Irssi::command_bind(signal, func, category)");
	} else if (items > 2)
		croak("Usage: Irssi::command_bind(signals_hash, category)");

	if (!hash) {
		category = items < 3 ? DEFAULT_COMMAND_CATEGORY :
			(char *)SvPV(p2, PL_na);
		perl_command_bind_to((char *)SvPV(p0, PL_na), category, p1, priority);
	} else {
		category = items < 2 ? DEFAULT_COMMAND_CATEGORY :
			(char *)SvPV(p1, PL_na);
		perl_command_bind_add_hash(priority, p0, category);
	}
}

#line 70 "Core.c"

XS(XS_Irssi_signal_emit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_emit)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: Irssi::signal_emit(signal, ...)");
    {
	char *	signal = (char *)SvPV_nolen(ST(0));
#line 67 "Core.xs"
	void *p[SIGNAL_MAX_ARGUMENTS];
	int n;

	memset(p, 0, sizeof(p));
	for (n = 1; n < items && n < SIGNAL_MAX_ARGUMENTS+1; n++) {
		if (SvPOKp(ST(n)))
			p[n-1] = SvPV(ST(n), PL_na);
		else if (irssi_is_ref_object(ST(n)))
			p[n-1] = irssi_ref_object(ST(n));
		else if (SvROK(ST(n)))
			p[n-1] = (void *) SvIV((SV*)SvRV(ST(n)));
		else if (SvIOK(ST(n)))
			p[n-1] = (void *)SvIV(ST(n));
		else
			p[n-1] = NULL;
	}
	signal_emit(signal, items-1, p[0], p[1], p[2], p[3], p[4], p[5]);
#line 98 "Core.c"
    }
    XSRETURN(1);
}


XS(XS_Irssi_signal_continue); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_continue)
{
    dXSARGS;
    {
#line 88 "Core.xs"
	void *p[SIGNAL_MAX_ARGUMENTS];
	int n;

	memset(p, 0, sizeof(p));
	for (n = 0; n < items && n < SIGNAL_MAX_ARGUMENTS; n++) {
		if (SvPOKp(ST(n)))
			p[n] = SvPV(ST(n), PL_na);
		else if (irssi_is_ref_object(ST(n)))
			p[n] = irssi_ref_object(ST(n));
		else if (SvROK(ST(n)))
			p[n] = (void *) SvIV((SV*)SvRV(ST(n)));
		else if (SvIOK(ST(n)))
			p[n] = (void *) SvIV(ST(n));
		else
			p[n] = NULL;
	}
	signal_continue(items, p[0], p[1], p[2], p[3], p[4], p[5]);
#line 127 "Core.c"
    }
    XSRETURN(1);
}


XS(XS_Irssi_signal_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_add)
{
    dXSARGS;
    {
#line 109 "Core.xs"
	if (items != 1 && items != 2)
		croak("Usage: Irssi::signal_add(signal, func)");
	if (items == 2)
		perl_signal_add_full((char *)SvPV(ST(0),PL_na), ST(1),
				     SIGNAL_PRIORITY_DEFAULT);
	else
		perl_signal_add_hash(SIGNAL_PRIORITY_DEFAULT, ST(0));
#line 146 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_add_first); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_add_first)
{
    dXSARGS;
    {
#line 120 "Core.xs"
	if (items != 1 && items != 2)
		croak("Usage: Irssi::signal_add_first(signal, func)");
	if (items == 2)
		perl_signal_add_full((char *)SvPV(ST(0),PL_na), ST(1),
				     SIGNAL_PRIORITY_HIGH);
	else
		perl_signal_add_hash(SIGNAL_PRIORITY_HIGH, ST(0));
#line 165 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_add_last); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_add_last)
{
    dXSARGS;
    {
#line 131 "Core.xs"
	if (items != 1 && items != 2)
		croak("Usage: Irssi::signal_add_last(signal, func)");
	if (items == 2)
		perl_signal_add_full((char *)SvPV(ST(0),PL_na), ST(1),
				     SIGNAL_PRIORITY_LOW);
	else
		perl_signal_add_hash(SIGNAL_PRIORITY_LOW, ST(0));
#line 184 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_add_priority); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_add_priority)
{
    dXSARGS;
    {
#line 142 "Core.xs"
	if (items != 2 && items != 3)
		croak("Usage: Irssi::signal_add_priority(signal, func, priority)");
	if (items == 3)
		perl_signal_add_full((char *)SvPV(ST(0),PL_na), ST(1), SvIV(ST(2)));
	else
		perl_signal_add_hash(SvIV(ST(0)), ST(1));
#line 202 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_register); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_register)
{
    dXSARGS;
    {
#line 152 "Core.xs"
	HV *hv;
        HE *he;
	I32 len, pos;
	const char *arr[7];
#line 218 "Core.c"
#line 157 "Core.xs"
	if (items != 1 || !is_hvref(ST(0)))
		croak("Usage: Irssi::signal_register(hash)");

        hv = hvref(ST(0));
	hv_iterinit(hv);
	while ((he = hv_iternext(hv)) != NULL) {
		const char *key = hv_iterkey(he, &len);
		SV *val = HeVAL(he);
		AV *av;

		if (!SvROK(val) || SvTYPE(SvRV(val)) != SVt_PVAV)
			croak("not array reference");

		av = (AV *) SvRV(val);
		len = av_len(av)+1;
		if (len > 6) len = 6;
		for (pos = 0; pos < len; pos++) {
                	SV **val = av_fetch(av, pos, 0);
			arr[pos] = SvPV(*val, PL_na);
		}
		arr[pos] = NULL;
		perl_signal_register(key, arr);
	}
#line 243 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_SIGNAL_PRIORITY_LOW); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_SIGNAL_PRIORITY_LOW)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::SIGNAL_PRIORITY_LOW()");
    {
	int	RETVAL;
	dXSTARG;
#line 185 "Core.xs"
	RETVAL = SIGNAL_PRIORITY_LOW;
#line 260 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_SIGNAL_PRIORITY_DEFAULT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_SIGNAL_PRIORITY_DEFAULT)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::SIGNAL_PRIORITY_DEFAULT()");
    {
	int	RETVAL;
	dXSTARG;
#line 192 "Core.xs"
	RETVAL = SIGNAL_PRIORITY_DEFAULT;
#line 278 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_SIGNAL_PRIORITY_HIGH); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_SIGNAL_PRIORITY_HIGH)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::SIGNAL_PRIORITY_HIGH()");
    {
	int	RETVAL;
	dXSTARG;
#line 199 "Core.xs"
	RETVAL = SIGNAL_PRIORITY_HIGH;
#line 296 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_signal_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_remove)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::signal_remove(signal, func)");
    {
	char *	signal = (char *)SvPV_nolen(ST(0));
	SV *	func = ST(1);
#line 208 "Core.xs"
	perl_signal_remove(signal, func);
#line 314 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_stop); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_stop)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::signal_stop()");
    {

	signal_stop();
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_stop_by_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_stop_by_name)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::signal_stop_by_name(signal)");
    {
	char *	signal = (char *)SvPV_nolen(ST(0));

	signal_stop_by_name(signal);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_signal_get_emitted); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_get_emitted)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::signal_get_emitted()");
    {
	char *	RETVAL;
	dXSTARG;
#line 220 "Core.xs"
	RETVAL = (char *) signal_get_emitted();
#line 360 "Core.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi_signal_get_emitted_id); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_signal_get_emitted_id)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::signal_get_emitted_id()");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = signal_get_emitted_id();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_timeout_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_timeout_add)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::timeout_add(msecs, func, data)");
    {
	int	msecs = (int)SvIV(ST(0));
	SV *	func = ST(1);
	SV *	data = ST(2);
	int	RETVAL;
	dXSTARG;
#line 233 "Core.xs"
	if (msecs < 10) {
		croak("Irssi::timeout() : msecs must be >= 10");
		RETVAL = -1;
	} else {
		RETVAL = perl_timeout_add(msecs, func, data, FALSE);
	}
#line 403 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_timeout_add_once); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_timeout_add_once)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::timeout_add_once(msecs, func, data)");
    {
	int	msecs = (int)SvIV(ST(0));
	SV *	func = ST(1);
	SV *	data = ST(2);
	int	RETVAL;
	dXSTARG;
#line 248 "Core.xs"
	if (msecs < 10) {
		croak("Irssi::timeout_once() : msecs must be >= 10");
		RETVAL = -1;
	} else {
		RETVAL = perl_timeout_add(msecs, func, data, TRUE);
	}
#line 429 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_timeout_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_timeout_remove)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::timeout_remove(tag)");
    {
	int	tag = (int)SvIV(ST(0));
#line 261 "Core.xs"
	perl_source_remove(tag);
#line 446 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_INPUT_READ); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_INPUT_READ)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::INPUT_READ()");
    {
	int	RETVAL;
	dXSTARG;
#line 267 "Core.xs"
	RETVAL = G_INPUT_READ;
#line 463 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_INPUT_WRITE); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_INPUT_WRITE)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::INPUT_WRITE()");
    {
	int	RETVAL;
	dXSTARG;
#line 274 "Core.xs"
	RETVAL = G_INPUT_WRITE;
#line 481 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_input_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_input_add)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Irssi::input_add(source, condition, func, data)");
    {
	int	source = (int)SvIV(ST(0));
	int	condition = (int)SvIV(ST(1));
	SV *	func = ST(2);
	SV *	data = ST(3);
	int	RETVAL;
	dXSTARG;
#line 285 "Core.xs"
	RETVAL = perl_input_add(source, condition, func, data, FALSE);
#line 503 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_input_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_input_remove)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::input_remove(tag)");
    {
	int	tag = (int)SvIV(ST(0));
#line 293 "Core.xs"
	perl_source_remove(tag);
#line 520 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_MSGLEVEL_CRAP); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_CRAP)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_CRAP()");
    {
	int	RETVAL;
	dXSTARG;
#line 299 "Core.xs"
	RETVAL = MSGLEVEL_CRAP;
#line 537 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_MSGS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_MSGS)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_MSGS()");
    {
	int	RETVAL;
	dXSTARG;
#line 306 "Core.xs"
	RETVAL = MSGLEVEL_MSGS;
#line 555 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_PUBLIC); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_PUBLIC)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_PUBLIC()");
    {
	int	RETVAL;
	dXSTARG;
#line 313 "Core.xs"
	RETVAL = MSGLEVEL_PUBLIC;
#line 573 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_NOTICES); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_NOTICES)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_NOTICES()");
    {
	int	RETVAL;
	dXSTARG;
#line 320 "Core.xs"
	RETVAL = MSGLEVEL_NOTICES;
#line 591 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_SNOTES); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_SNOTES)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_SNOTES()");
    {
	int	RETVAL;
	dXSTARG;
#line 327 "Core.xs"
	RETVAL = MSGLEVEL_SNOTES;
#line 609 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_CTCPS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_CTCPS)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_CTCPS()");
    {
	int	RETVAL;
	dXSTARG;
#line 334 "Core.xs"
	RETVAL = MSGLEVEL_CTCPS;
#line 627 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_ACTIONS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_ACTIONS)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_ACTIONS()");
    {
	int	RETVAL;
	dXSTARG;
#line 341 "Core.xs"
	RETVAL = MSGLEVEL_ACTIONS;
#line 645 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_JOINS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_JOINS)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_JOINS()");
    {
	int	RETVAL;
	dXSTARG;
#line 348 "Core.xs"
	RETVAL = MSGLEVEL_JOINS;
#line 663 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_PARTS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_PARTS)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_PARTS()");
    {
	int	RETVAL;
	dXSTARG;
#line 355 "Core.xs"
	RETVAL = MSGLEVEL_PARTS;
#line 681 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_QUITS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_QUITS)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_QUITS()");
    {
	int	RETVAL;
	dXSTARG;
#line 362 "Core.xs"
	RETVAL = MSGLEVEL_QUITS;
#line 699 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_KICKS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_KICKS)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_KICKS()");
    {
	int	RETVAL;
	dXSTARG;
#line 369 "Core.xs"
	RETVAL = MSGLEVEL_KICKS;
#line 717 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_MODES); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_MODES)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_MODES()");
    {
	int	RETVAL;
	dXSTARG;
#line 376 "Core.xs"
	RETVAL = MSGLEVEL_MODES;
#line 735 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_TOPICS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_TOPICS)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_TOPICS()");
    {
	int	RETVAL;
	dXSTARG;
#line 383 "Core.xs"
	RETVAL = MSGLEVEL_TOPICS;
#line 753 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_WALLOPS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_WALLOPS)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_WALLOPS()");
    {
	int	RETVAL;
	dXSTARG;
#line 390 "Core.xs"
	RETVAL = MSGLEVEL_WALLOPS;
#line 771 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_INVITES); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_INVITES)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_INVITES()");
    {
	int	RETVAL;
	dXSTARG;
#line 397 "Core.xs"
	RETVAL = MSGLEVEL_INVITES;
#line 789 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_NICKS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_NICKS)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_NICKS()");
    {
	int	RETVAL;
	dXSTARG;
#line 404 "Core.xs"
	RETVAL = MSGLEVEL_NICKS;
#line 807 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_DCC); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_DCC)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_DCC()");
    {
	int	RETVAL;
	dXSTARG;
#line 411 "Core.xs"
	RETVAL = MSGLEVEL_DCC;
#line 825 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_DCCMSGS); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_DCCMSGS)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_DCCMSGS()");
    {
	int	RETVAL;
	dXSTARG;
#line 418 "Core.xs"
	RETVAL = MSGLEVEL_DCCMSGS;
#line 843 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_CLIENTNOTICE); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_CLIENTNOTICE)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_CLIENTNOTICE()");
    {
	int	RETVAL;
	dXSTARG;
#line 425 "Core.xs"
	RETVAL = MSGLEVEL_CLIENTNOTICE;
#line 861 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_CLIENTCRAP); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_CLIENTCRAP)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_CLIENTCRAP()");
    {
	int	RETVAL;
	dXSTARG;
#line 432 "Core.xs"
	RETVAL = MSGLEVEL_CLIENTCRAP;
#line 879 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_CLIENTERROR); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_CLIENTERROR)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_CLIENTERROR()");
    {
	int	RETVAL;
	dXSTARG;
#line 439 "Core.xs"
	RETVAL = MSGLEVEL_CLIENTERROR;
#line 897 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_HILIGHT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_HILIGHT)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_HILIGHT()");
    {
	int	RETVAL;
	dXSTARG;
#line 446 "Core.xs"
	RETVAL = MSGLEVEL_HILIGHT;
#line 915 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_ALL); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_ALL)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_ALL()");
    {
	int	RETVAL;
	dXSTARG;
#line 453 "Core.xs"
	RETVAL = MSGLEVEL_ALL;
#line 933 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_NOHILIGHT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_NOHILIGHT)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_NOHILIGHT()");
    {
	int	RETVAL;
	dXSTARG;
#line 460 "Core.xs"
	RETVAL = MSGLEVEL_NOHILIGHT;
#line 951 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_NO_ACT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_NO_ACT)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_NO_ACT()");
    {
	int	RETVAL;
	dXSTARG;
#line 467 "Core.xs"
	RETVAL = MSGLEVEL_NO_ACT;
#line 969 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_NEVER); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_NEVER)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_NEVER()");
    {
	int	RETVAL;
	dXSTARG;
#line 474 "Core.xs"
	RETVAL = MSGLEVEL_NEVER;
#line 987 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_MSGLEVEL_LASTLOG); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_MSGLEVEL_LASTLOG)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::MSGLEVEL_LASTLOG()");
    {
	int	RETVAL;
	dXSTARG;
#line 481 "Core.xs"
	RETVAL = MSGLEVEL_LASTLOG;
#line 1005 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_level2bits); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_level2bits)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::level2bits(str)");
    {
	char *	str = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = level2bits(str);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_bits2level); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_bits2level)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::bits2level(bits)");
    SP -= items;
    {
	int	bits = (int)SvIV(ST(0));
#line 493 "Core.xs"
	char *ret;
#line 1041 "Core.c"
#line 495 "Core.xs"
	ret = bits2level(bits);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free(ret);
#line 1046 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_combine_level); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_combine_level)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::combine_level(level, str)");
    {
	int	level = (int)SvIV(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = combine_level(level, str);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_command); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::command(cmd)");
    {
	char *	cmd = (char *)SvPV_nolen(ST(0));
#line 508 "Core.xs"
	perl_command(cmd, NULL, NULL);
#line 1082 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_commands); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_commands)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::commands()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 513 "Core.xs"
	GSList *tmp;
#line 1099 "Core.c"
#line 515 "Core.xs"
	for (tmp = commands; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::Command")));
	}
#line 1104 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_command_bind_first); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_bind_first)
{
    dXSARGS;
    {
#line 522 "Core.xs"
	handle_command_bind(SIGNAL_PRIORITY_HIGH, items, ST(0), ST(1), ST(2));
#line 1118 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_command_bind); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_bind)
{
    dXSARGS;
    {
#line 527 "Core.xs"
	handle_command_bind(SIGNAL_PRIORITY_DEFAULT, items, ST(0), ST(1), ST(2));
#line 1131 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_command_bind_last); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_bind_last)
{
    dXSARGS;
    {
#line 532 "Core.xs"
	handle_command_bind(SIGNAL_PRIORITY_LOW, items, ST(0), ST(1), ST(2));
#line 1144 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_command_runsub); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_runsub)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Irssi::command_runsub(cmd, data, server, item)");
    {
	char *	cmd = (char *)SvPV_nolen(ST(0));
	char *	data = (char *)SvPV_nolen(ST(1));
	Irssi__Server	server = irssi_ref_object(ST(2));
	Irssi__Windowitem	item = irssi_ref_object(ST(3));
#line 541 "Core.xs"
	perl_command_runsub(cmd, data, server, item);
#line 1163 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_command_unbind); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_unbind)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::command_unbind(cmd, func)");
    {
	char *	cmd = (char *)SvPV_nolen(ST(0));
	SV *	func = ST(1);
#line 548 "Core.xs"
	perl_command_unbind(cmd, func);
#line 1180 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_command_set_options); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_command_set_options)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::command_set_options(cmd, options)");
    {
	char *	cmd = (char *)SvPV_nolen(ST(0));
	char *	options = (char *)SvPV_nolen(ST(1));

	command_set_options(cmd, options);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_pidwait_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_pidwait_add)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::pidwait_add(pid)");
    {
	int	pid = (int)SvIV(ST(0));

	pidwait_add(pid);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_pidwait_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_pidwait_remove)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::pidwait_remove(pid)");
    {
	int	pid = (int)SvIV(ST(0));

	pidwait_remove(pid);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_parse_special); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_parse_special)
{
    dXSARGS;
    if (items < 1 || items > 3)
	Perl_croak(aTHX_ "Usage: Irssi::parse_special(cmd, data=\"\", flags=0)");
    SP -= items;
    {
	char *	cmd = (char *)SvPV_nolen(ST(0));
	char *	data;
	int	flags;
#line 569 "Core.xs"
	char *ret;
#line 1245 "Core.c"

	if (items < 2)
	    data = "";
	else {
	    data = (char *)SvPV_nolen(ST(1));
	}

	if (items < 3)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(2));
	}
#line 571 "Core.xs"
	ret = parse_special_string(cmd, NULL, NULL, data, NULL, flags);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free_not_null(ret);
#line 1262 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_get_irssi_dir); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_get_irssi_dir)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::get_irssi_dir()");
    {
	char *	RETVAL;
	dXSTARG;
#line 578 "Core.xs"
	RETVAL = (char *) get_irssi_dir();
#line 1280 "Core.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi_get_irssi_config); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_get_irssi_config)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::get_irssi_config()");
    {
	char *	RETVAL;
	dXSTARG;
#line 585 "Core.xs"
	RETVAL = (char *) get_irssi_config();
#line 1298 "Core.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi_get_irssi_binary); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_get_irssi_binary)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::get_irssi_binary()");
    {
	char *	RETVAL;
	dXSTARG;
#line 592 "Core.xs"
	RETVAL = irssi_binary;
#line 1316 "Core.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi_version); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_version)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::version()");
    {
#line 599 "Core.xs"
	char version[100];
#line 1332 "Core.c"
	char *	RETVAL;
	dXSTARG;
#line 601 "Core.xs"
	g_snprintf(version, sizeof(version), "%d.%04d",
		   IRSSI_VERSION_DATE, IRSSI_VERSION_TIME);
	RETVAL = version;
#line 1339 "Core.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi_get_gui); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_get_gui)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::get_gui()");
    {
	int	RETVAL;
	dXSTARG;
#line 610 "Core.xs"
	RETVAL = irssi_gui;
#line 1357 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_NONE); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_NONE)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::IRSSI_GUI_NONE()");
    {
	int	RETVAL;
	dXSTARG;
#line 617 "Core.xs"
	RETVAL = IRSSI_GUI_NONE;
#line 1375 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_TEXT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_TEXT)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::IRSSI_GUI_TEXT()");
    {
	int	RETVAL;
	dXSTARG;
#line 624 "Core.xs"
	RETVAL = IRSSI_GUI_TEXT;
#line 1393 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_GTK); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_GTK)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::IRSSI_GUI_GTK()");
    {
	int	RETVAL;
	dXSTARG;
#line 631 "Core.xs"
	RETVAL = IRSSI_GUI_GTK;
#line 1411 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_GNOME); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_GNOME)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::IRSSI_GUI_GNOME()");
    {
	int	RETVAL;
	dXSTARG;
#line 638 "Core.xs"
	RETVAL = IRSSI_GUI_GNOME;
#line 1429 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_QT); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_QT)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::IRSSI_GUI_QT()");
    {
	int	RETVAL;
	dXSTARG;
#line 645 "Core.xs"
	RETVAL = IRSSI_GUI_QT;
#line 1447 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_IRSSI_GUI_KDE); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_IRSSI_GUI_KDE)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::IRSSI_GUI_KDE()");
    {
	int	RETVAL;
	dXSTARG;
#line 652 "Core.xs"
	RETVAL = IRSSI_GUI_KDE;
#line 1465 "Core.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_parse_special); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_parse_special)
{
    dXSARGS;
    if (items < 2 || items > 4)
	Perl_croak(aTHX_ "Usage: Irssi::Server::parse_special(server, cmd, data=\"\", flags=0)");
    SP -= items;
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
	char *	data;
	int	flags;
#line 667 "Core.xs"
	char *ret;
#line 1486 "Core.c"

	if (items < 3)
	    data = "";
	else {
	    data = (char *)SvPV_nolen(ST(2));
	}

	if (items < 4)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(3));
	}
#line 669 "Core.xs"
	ret = parse_special_string(cmd, server, NULL, data, NULL, flags);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free_not_null(ret);
#line 1503 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Server_command); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_command)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Server::command(server, cmd)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
#line 678 "Core.xs"
	perl_command(cmd, server, NULL);
#line 1521 "Core.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Windowitem_parse_special); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_parse_special)
{
    dXSARGS;
    if (items < 2 || items > 4)
	Perl_croak(aTHX_ "Usage: Irssi::Windowitem::parse_special(item, cmd, data=\"\", flags=0)");
    SP -= items;
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
	char *	data;
	int	flags;
#line 692 "Core.xs"
	char *ret;
#line 1541 "Core.c"

	if (items < 3)
	    data = "";
	else {
	    data = (char *)SvPV_nolen(ST(2));
	}

	if (items < 4)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(3));
	}
#line 694 "Core.xs"
	ret = parse_special_string(cmd, item->server, item, data, NULL, flags);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free_not_null(ret);
#line 1558 "Core.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Windowitem_command); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_command)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Windowitem::command(item, cmd)");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
#line 703 "Core.xs"
	perl_command(cmd, item->server, item);
#line 1576 "Core.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Core); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Core)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::signal_emit", XS_Irssi_signal_emit, file, "$;@");
        newXSproto("Irssi::signal_continue", XS_Irssi_signal_continue, file, ";@");
        newXSproto("Irssi::signal_add", XS_Irssi_signal_add, file, ";@");
        newXSproto("Irssi::signal_add_first", XS_Irssi_signal_add_first, file, ";@");
        newXSproto("Irssi::signal_add_last", XS_Irssi_signal_add_last, file, ";@");
        newXSproto("Irssi::signal_add_priority", XS_Irssi_signal_add_priority, file, ";@");
        newXSproto("Irssi::signal_register", XS_Irssi_signal_register, file, ";@");
        newXSproto("Irssi::SIGNAL_PRIORITY_LOW", XS_Irssi_SIGNAL_PRIORITY_LOW, file, "");
        newXSproto("Irssi::SIGNAL_PRIORITY_DEFAULT", XS_Irssi_SIGNAL_PRIORITY_DEFAULT, file, "");
        newXSproto("Irssi::SIGNAL_PRIORITY_HIGH", XS_Irssi_SIGNAL_PRIORITY_HIGH, file, "");
        newXSproto("Irssi::signal_remove", XS_Irssi_signal_remove, file, "$$");
        newXSproto("Irssi::signal_stop", XS_Irssi_signal_stop, file, "");
        newXSproto("Irssi::signal_stop_by_name", XS_Irssi_signal_stop_by_name, file, "$");
        newXSproto("Irssi::signal_get_emitted", XS_Irssi_signal_get_emitted, file, "");
        newXSproto("Irssi::signal_get_emitted_id", XS_Irssi_signal_get_emitted_id, file, "");
        newXSproto("Irssi::timeout_add", XS_Irssi_timeout_add, file, "$$$");
        newXSproto("Irssi::timeout_add_once", XS_Irssi_timeout_add_once, file, "$$$");
        newXSproto("Irssi::timeout_remove", XS_Irssi_timeout_remove, file, "$");
        newXSproto("Irssi::INPUT_READ", XS_Irssi_INPUT_READ, file, "");
        newXSproto("Irssi::INPUT_WRITE", XS_Irssi_INPUT_WRITE, file, "");
        newXSproto("Irssi::input_add", XS_Irssi_input_add, file, "$$$$");
        newXSproto("Irssi::input_remove", XS_Irssi_input_remove, file, "$");
        newXSproto("Irssi::MSGLEVEL_CRAP", XS_Irssi_MSGLEVEL_CRAP, file, "");
        newXSproto("Irssi::MSGLEVEL_MSGS", XS_Irssi_MSGLEVEL_MSGS, file, "");
        newXSproto("Irssi::MSGLEVEL_PUBLIC", XS_Irssi_MSGLEVEL_PUBLIC, file, "");
        newXSproto("Irssi::MSGLEVEL_NOTICES", XS_Irssi_MSGLEVEL_NOTICES, file, "");
        newXSproto("Irssi::MSGLEVEL_SNOTES", XS_Irssi_MSGLEVEL_SNOTES, file, "");
        newXSproto("Irssi::MSGLEVEL_CTCPS", XS_Irssi_MSGLEVEL_CTCPS, file, "");
        newXSproto("Irssi::MSGLEVEL_ACTIONS", XS_Irssi_MSGLEVEL_ACTIONS, file, "");
        newXSproto("Irssi::MSGLEVEL_JOINS", XS_Irssi_MSGLEVEL_JOINS, file, "");
        newXSproto("Irssi::MSGLEVEL_PARTS", XS_Irssi_MSGLEVEL_PARTS, file, "");
        newXSproto("Irssi::MSGLEVEL_QUITS", XS_Irssi_MSGLEVEL_QUITS, file, "");
        newXSproto("Irssi::MSGLEVEL_KICKS", XS_Irssi_MSGLEVEL_KICKS, file, "");
        newXSproto("Irssi::MSGLEVEL_MODES", XS_Irssi_MSGLEVEL_MODES, file, "");
        newXSproto("Irssi::MSGLEVEL_TOPICS", XS_Irssi_MSGLEVEL_TOPICS, file, "");
        newXSproto("Irssi::MSGLEVEL_WALLOPS", XS_Irssi_MSGLEVEL_WALLOPS, file, "");
        newXSproto("Irssi::MSGLEVEL_INVITES", XS_Irssi_MSGLEVEL_INVITES, file, "");
        newXSproto("Irssi::MSGLEVEL_NICKS", XS_Irssi_MSGLEVEL_NICKS, file, "");
        newXSproto("Irssi::MSGLEVEL_DCC", XS_Irssi_MSGLEVEL_DCC, file, "");
        newXSproto("Irssi::MSGLEVEL_DCCMSGS", XS_Irssi_MSGLEVEL_DCCMSGS, file, "");
        newXSproto("Irssi::MSGLEVEL_CLIENTNOTICE", XS_Irssi_MSGLEVEL_CLIENTNOTICE, file, "");
        newXSproto("Irssi::MSGLEVEL_CLIENTCRAP", XS_Irssi_MSGLEVEL_CLIENTCRAP, file, "");
        newXSproto("Irssi::MSGLEVEL_CLIENTERROR", XS_Irssi_MSGLEVEL_CLIENTERROR, file, "");
        newXSproto("Irssi::MSGLEVEL_HILIGHT", XS_Irssi_MSGLEVEL_HILIGHT, file, "");
        newXSproto("Irssi::MSGLEVEL_ALL", XS_Irssi_MSGLEVEL_ALL, file, "");
        newXSproto("Irssi::MSGLEVEL_NOHILIGHT", XS_Irssi_MSGLEVEL_NOHILIGHT, file, "");
        newXSproto("Irssi::MSGLEVEL_NO_ACT", XS_Irssi_MSGLEVEL_NO_ACT, file, "");
        newXSproto("Irssi::MSGLEVEL_NEVER", XS_Irssi_MSGLEVEL_NEVER, file, "");
        newXSproto("Irssi::MSGLEVEL_LASTLOG", XS_Irssi_MSGLEVEL_LASTLOG, file, "");
        newXSproto("Irssi::level2bits", XS_Irssi_level2bits, file, "$");
        newXSproto("Irssi::bits2level", XS_Irssi_bits2level, file, "$");
        newXSproto("Irssi::combine_level", XS_Irssi_combine_level, file, "$$");
        newXSproto("Irssi::command", XS_Irssi_command, file, "$");
        newXSproto("Irssi::commands", XS_Irssi_commands, file, "");
        newXSproto("Irssi::command_bind_first", XS_Irssi_command_bind_first, file, ";@");
        newXSproto("Irssi::command_bind", XS_Irssi_command_bind, file, ";@");
        newXSproto("Irssi::command_bind_last", XS_Irssi_command_bind_last, file, ";@");
        newXSproto("Irssi::command_runsub", XS_Irssi_command_runsub, file, "$$$$");
        newXSproto("Irssi::command_unbind", XS_Irssi_command_unbind, file, "$$");
        newXSproto("Irssi::command_set_options", XS_Irssi_command_set_options, file, "$$");
        newXSproto("Irssi::pidwait_add", XS_Irssi_pidwait_add, file, "$");
        newXSproto("Irssi::pidwait_remove", XS_Irssi_pidwait_remove, file, "$");
        newXSproto("Irssi::parse_special", XS_Irssi_parse_special, file, "$;$$");
        newXSproto("Irssi::get_irssi_dir", XS_Irssi_get_irssi_dir, file, "");
        newXSproto("Irssi::get_irssi_config", XS_Irssi_get_irssi_config, file, "");
        newXSproto("Irssi::get_irssi_binary", XS_Irssi_get_irssi_binary, file, "");
        newXSproto("Irssi::version", XS_Irssi_version, file, "");
        newXSproto("Irssi::get_gui", XS_Irssi_get_gui, file, "");
        newXSproto("Irssi::IRSSI_GUI_NONE", XS_Irssi_IRSSI_GUI_NONE, file, "");
        newXSproto("Irssi::IRSSI_GUI_TEXT", XS_Irssi_IRSSI_GUI_TEXT, file, "");
        newXSproto("Irssi::IRSSI_GUI_GTK", XS_Irssi_IRSSI_GUI_GTK, file, "");
        newXSproto("Irssi::IRSSI_GUI_GNOME", XS_Irssi_IRSSI_GUI_GNOME, file, "");
        newXSproto("Irssi::IRSSI_GUI_QT", XS_Irssi_IRSSI_GUI_QT, file, "");
        newXSproto("Irssi::IRSSI_GUI_KDE", XS_Irssi_IRSSI_GUI_KDE, file, "");
        newXSproto("Irssi::Server::parse_special", XS_Irssi__Server_parse_special, file, "$$;$$");
        newXSproto("Irssi::Server::command", XS_Irssi__Server_command, file, "$$");
        newXSproto("Irssi::Windowitem::parse_special", XS_Irssi__Windowitem_parse_special, file, "$$;$$");
        newXSproto("Irssi::Windowitem::command", XS_Irssi__Windowitem_command, file, "$$");
    XSRETURN_YES;
}

