/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Ignore.xs. Do not edit this file, edit Ignore.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Ignore.xs"
#include "module.h"

#line 13 "Ignore.c"

XS(XS_Irssi_ignores); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_ignores)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::ignores()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 9 "Ignore.xs"
	GSList *tmp;
#line 26 "Ignore.c"
#line 11 "Ignore.xs"
	for (tmp = ignores; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::Ignore")));
	}
#line 31 "Ignore.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_ignore_check); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_ignore_check)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Irssi::ignore_check(nick, host, channel, text, level)");
    {
	char *	nick = (char *)SvPV_nolen(ST(0));
	char *	host = (char *)SvPV_nolen(ST(1));
	char *	channel = (char *)SvPV_nolen(ST(2));
	char *	text = (char *)SvPV_nolen(ST(3));
	int	level = (int)SvIV(ST(4));
	int	RETVAL;
	dXSTARG;
#line 23 "Ignore.xs"
	RETVAL = ignore_check(NULL, nick, host, channel, text, level);
#line 54 "Ignore.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_ignore_check); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_ignore_check)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Irssi::Server::ignore_check(server, nick, host, channel, text, level)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	char *	host = (char *)SvPV_nolen(ST(2));
	char *	channel = (char *)SvPV_nolen(ST(3));
	char *	text = (char *)SvPV_nolen(ST(4));
	int	level = (int)SvIV(ST(5));
	int	RETVAL;
	dXSTARG;

	RETVAL = ignore_check(server, nick, host, channel, text, level);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Ignore_add_rec); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Ignore_add_rec)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Ignore::add_rec(rec)");
    {
	Irssi__Ignore	rec = irssi_ref_object(ST(0));

	ignore_add_rec(rec);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Ignore_update_rec); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Ignore_update_rec)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Ignore::update_rec(rec)");
    {
	Irssi__Ignore	rec = irssi_ref_object(ST(0));

	ignore_update_rec(rec);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Ignore); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Ignore)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::ignores", XS_Irssi_ignores, file, "");
        newXSproto("Irssi::ignore_check", XS_Irssi_ignore_check, file, "$$$$$");
        newXSproto("Irssi::Server::ignore_check", XS_Irssi__Server_ignore_check, file, "$$$$$$");
        newXSproto("Irssi::Ignore::add_rec", XS_Irssi__Ignore_add_rec, file, "$");
        newXSproto("Irssi::Ignore::update_rec", XS_Irssi__Ignore_update_rec, file, "$");
    XSRETURN_YES;
}

