/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Irssi.xs. Do not edit this file, edit Irssi.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Irssi.xs"
#include "module.h"

static int initialized = FALSE;

void perl_expando_init(void);
void perl_expando_deinit(void);

void perl_settings_init(void);
void perl_settings_deinit(void);

#line 21 "Irssi.c"

XS(XS_Irssi_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_init)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::init()");
    {
#line 18 "Irssi.xs"
	if (initialized) return;
	perl_api_version_check("Irssi");
	initialized = TRUE;

        perl_settings_init();
	perl_expando_init();
#line 37 "Irssi.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_deinit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_deinit)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::deinit()");
    {
#line 28 "Irssi.xs"
	if (!initialized) return;
	perl_expando_deinit();
        perl_settings_deinit();
	initialized = FALSE;
#line 55 "Irssi.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::init", XS_Irssi_init, file, "");
        newXSproto("Irssi::deinit", XS_Irssi_deinit, file, "");

    /* Initialisation Section */

#line 34 "Irssi.xs"
        irssi_boot(Channel);
	irssi_boot(Core);
	irssi_boot(Expando);
	irssi_boot(Ignore);
	irssi_boot(Log);
	irssi_boot(Masks);
	irssi_boot(Query);
	irssi_boot(Rawlog);
	irssi_boot(Server);
	irssi_boot(Settings);

#line 88 "Irssi.c"

    /* End of Initialisation Section */

    XSRETURN_YES;
}

