/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Log.xs. Do not edit this file, edit Log.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Log.xs"
#include "module.h"

#line 13 "Log.c"

XS(XS_Irssi_logs); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_logs)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::logs()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 9 "Log.xs"
	GSList *tmp;
#line 26 "Log.c"
#line 11 "Log.xs"
	for (tmp = logs; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::Log")));
	}
#line 31 "Log.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_log_create_rec); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_log_create_rec)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::log_create_rec(fname, level)");
    {
	char *	fname = (char *)SvPV_nolen(ST(0));
	int	level = (int)SvIV(ST(1));
	Irssi__Log	RETVAL;

	RETVAL = log_create_rec(fname, level);
	ST(0) = plain_bless(RETVAL, "Irssi::Log");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_log_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_log_find)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::log_find(fname)");
    {
	char *	fname = (char *)SvPV_nolen(ST(0));
	Irssi__Log	RETVAL;

	RETVAL = log_find(fname);
	ST(0) = plain_bless(RETVAL, "Irssi::Log");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Log_item_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_item_add)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Irssi::Log::item_add(log, type, name, servertag)");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));
	int	type = (int)SvIV(ST(1));
	char *	name = (char *)SvPV_nolen(ST(2));
	char *	servertag = (char *)SvPV_nolen(ST(3));

	log_item_add(log, type, name, servertag);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_item_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_item_destroy)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Log::item_destroy(log, item)");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));
	Irssi__Logitem	item = irssi_ref_object(ST(1));

	log_item_destroy(log, item);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_item_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_item_find)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Irssi::Log::item_find(log, type, item, servertag)");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));
	int	type = (int)SvIV(ST(1));
	char *	item = (char *)SvPV_nolen(ST(2));
	char *	servertag = (char *)SvPV_nolen(ST(3));
	Irssi__Logitem	RETVAL;

	RETVAL = log_item_find(log, type, item, servertag);
	ST(0) = plain_bless(RETVAL, "Irssi::Logitem");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Log_update); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_update)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Log::update(log)");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));

	log_update(log);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_close); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_close)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Log::close(log)");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));

	log_close(log);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_write_rec); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_write_rec)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::Log::write_rec(log, str, level)");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));
	int	level = (int)SvIV(ST(2));

	log_write_rec(log, str, level);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_start_logging); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_start_logging)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Log::start_logging(log)");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));

	log_start_logging(log);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Log_stop_logging); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Log_stop_logging)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Log::stop_logging(log)");
    {
	Irssi__Log	log = irssi_ref_object(ST(0));

	log_stop_logging(log);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Log); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Log)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::logs", XS_Irssi_logs, file, "");
        newXSproto("Irssi::log_create_rec", XS_Irssi_log_create_rec, file, "$$");
        newXSproto("Irssi::log_find", XS_Irssi_log_find, file, "$");
        newXSproto("Irssi::Log::item_add", XS_Irssi__Log_item_add, file, "$$$$");
        newXSproto("Irssi::Log::item_destroy", XS_Irssi__Log_item_destroy, file, "$$");
        newXSproto("Irssi::Log::item_find", XS_Irssi__Log_item_find, file, "$$$$");
        newXSproto("Irssi::Log::update", XS_Irssi__Log_update, file, "$");
        newXSproto("Irssi::Log::close", XS_Irssi__Log_close, file, "$");
        newXSproto("Irssi::Log::write_rec", XS_Irssi__Log_write_rec, file, "$$$");
        newXSproto("Irssi::Log::start_logging", XS_Irssi__Log_start_logging, file, "$");
        newXSproto("Irssi::Log::stop_logging", XS_Irssi__Log_stop_logging, file, "$");
    XSRETURN_YES;
}

