/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Rawlog.xs. Do not edit this file, edit Rawlog.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Rawlog.xs"
#include "module.h"

#line 13 "Rawlog.c"

XS(XS_Irssi_rawlog_set_size); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_rawlog_set_size)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::rawlog_set_size(lines)");
    {
	int	lines = (int)SvIV(ST(0));

	rawlog_set_size(lines);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_rawlog_create); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_rawlog_create)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::rawlog_create()");
    {
	Irssi__Rawlog	RETVAL;

	RETVAL = rawlog_create();
	ST(0) = plain_bless(RETVAL, "Irssi::Rawlog");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Rawlog_get_lines); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_get_lines)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Rawlog::get_lines(rawlog)");
    SP -= items;
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
#line 21 "Rawlog.xs"
	GSList *tmp;
#line 59 "Rawlog.c"
#line 23 "Rawlog.xs"
	for (tmp = rawlog->lines; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(new_pv(tmp->data)));
	}
#line 64 "Rawlog.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__Rawlog_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_destroy)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Rawlog::destroy(rawlog)");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));

	rawlog_destroy(rawlog);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_input); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_input)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Rawlog::input(rawlog, str)");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));

	rawlog_input(rawlog, str);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_output); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_output)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Rawlog::output(rawlog, str)");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));

	rawlog_output(rawlog, str);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_redirect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_redirect)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Rawlog::redirect(rawlog, str)");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));

	rawlog_redirect(rawlog, str);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_open); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_open)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Rawlog::open(rawlog, fname)");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
	char *	fname = (char *)SvPV_nolen(ST(1));

	rawlog_open(rawlog, fname);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_close); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_close)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Rawlog::close(rawlog)");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));

	rawlog_close(rawlog);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Rawlog_save); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Rawlog_save)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Rawlog::save(rawlog, fname)");
    {
	Irssi__Rawlog	rawlog = irssi_ref_object(ST(0));
	char *	fname = (char *)SvPV_nolen(ST(1));

	rawlog_save(rawlog, fname);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Rawlog); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Rawlog)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::rawlog_set_size", XS_Irssi_rawlog_set_size, file, "$");
        newXSproto("Irssi::rawlog_create", XS_Irssi_rawlog_create, file, "");
        newXSproto("Irssi::Rawlog::get_lines", XS_Irssi__Rawlog_get_lines, file, "$");
        newXSproto("Irssi::Rawlog::destroy", XS_Irssi__Rawlog_destroy, file, "$");
        newXSproto("Irssi::Rawlog::input", XS_Irssi__Rawlog_input, file, "$$");
        newXSproto("Irssi::Rawlog::output", XS_Irssi__Rawlog_output, file, "$$");
        newXSproto("Irssi::Rawlog::redirect", XS_Irssi__Rawlog_redirect, file, "$$");
        newXSproto("Irssi::Rawlog::open", XS_Irssi__Rawlog_open, file, "$$");
        newXSproto("Irssi::Rawlog::close", XS_Irssi__Rawlog_close, file, "$");
        newXSproto("Irssi::Rawlog::save", XS_Irssi__Rawlog_save, file, "$$");
    XSRETURN_YES;
}

