/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Server.xs. Do not edit this file, edit Server.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Server.xs"
#include "module.h"

#line 13 "Server.c"

XS(XS_Irssi_servers); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_servers)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::servers()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 9 "Server.xs"
	GSList *tmp;
#line 26 "Server.c"
#line 11 "Server.xs"
	for (tmp = servers; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(iobject_bless((SERVER_REC *) tmp->data)));
	}
#line 31 "Server.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_reconnects); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_reconnects)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::reconnects()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 18 "Server.xs"
	GSList *tmp;
#line 49 "Server.c"
#line 20 "Server.xs"
	for (tmp = reconnects; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::Reconnect")));
	}
#line 54 "Server.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_chatnets); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_chatnets)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::chatnets()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 27 "Server.xs"
	GSList *tmp;
#line 72 "Server.c"
#line 29 "Server.xs"
	for (tmp = chatnets; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(iobject_bless((CHATNET_REC *) tmp->data)));
	}
#line 77 "Server.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_server_create_conn); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_server_create_conn)
{
    dXSARGS;
    if (items < 3 || items > 6)
	Perl_croak(aTHX_ "Usage: Irssi::server_create_conn(chat_type, dest, port, chatnet=NULL, password=NULL, nick=NULL)");
    {
	int	chat_type = (int)SvIV(ST(0));
	char *	dest = (char *)SvPV_nolen(ST(1));
	int	port = (int)SvIV(ST(2));
	char *	chatnet;
	char *	password;
	char *	nick;
	Irssi__Connect	RETVAL;

	if (items < 4)
	    chatnet = NULL;
	else {
	    chatnet = (char *)SvPV_nolen(ST(3));
	}

	if (items < 5)
	    password = NULL;
	else {
	    password = (char *)SvPV_nolen(ST(4));
	}

	if (items < 6)
	    nick = NULL;
	else {
	    nick = (char *)SvPV_nolen(ST(5));
	}

	RETVAL = server_create_conn(chat_type, dest, port, chatnet, password, nick);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_server_find_tag); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_server_find_tag)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::server_find_tag(tag)");
    {
	char *	tag = (char *)SvPV_nolen(ST(0));
	Irssi__Server	RETVAL;

	RETVAL = server_find_tag(tag);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_server_find_chatnet); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_server_find_chatnet)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::server_find_chatnet(chatnet)");
    {
	char *	chatnet = (char *)SvPV_nolen(ST(0));
	Irssi__Server	RETVAL;

	RETVAL = server_find_chatnet(chatnet);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_chatnet_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_chatnet_find)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::chatnet_find(name)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	Irssi__Chatnet	RETVAL;

	RETVAL = chatnet_find(name);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_disconnect); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_disconnect)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Server::disconnect(server)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));

	server_disconnect(server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Server_ref); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_ref)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Server::ref(server)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));

	server_ref(server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Server_unref); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_unref)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Server::unref(server)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));

	server_unref(server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Server_isnickflag); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_isnickflag)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Server::isnickflag(server, flag)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char	flag = (char)*SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;
#line 75 "Server.xs"
	RETVAL = server->isnickflag(server, flag);
#line 241 "Server.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_ischannel); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_ischannel)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Server::ischannel(server, data)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	data = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;
#line 84 "Server.xs"
	RETVAL = server->ischannel(server, data);
#line 261 "Server.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_get_nick_flags); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_get_nick_flags)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Server::get_nick_flags(server)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	RETVAL;
	dXSTARG;
#line 92 "Server.xs"
	RETVAL = (char *) server->get_nick_flags(server);
#line 280 "Server.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_send_message); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_send_message)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Irssi::Server::send_message(server, target, msg, target_type)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	target = (char *)SvPV_nolen(ST(1));
	char *	msg = (char *)SvPV_nolen(ST(2));
	int	target_type = (int)SvIV(ST(3));
#line 103 "Server.xs"
	server->send_message(server, target, msg, target_type);
#line 300 "Server.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Server); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Server)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::servers", XS_Irssi_servers, file, "");
        newXSproto("Irssi::reconnects", XS_Irssi_reconnects, file, "");
        newXSproto("Irssi::chatnets", XS_Irssi_chatnets, file, "");
        newXSproto("Irssi::server_create_conn", XS_Irssi_server_create_conn, file, "$$$;$$$");
        newXSproto("Irssi::server_find_tag", XS_Irssi_server_find_tag, file, "$");
        newXSproto("Irssi::server_find_chatnet", XS_Irssi_server_find_chatnet, file, "$");
        newXSproto("Irssi::chatnet_find", XS_Irssi_chatnet_find, file, "$");
        newXSproto("Irssi::Server::disconnect", XS_Irssi__Server_disconnect, file, "$");
        newXSproto("Irssi::Server::ref", XS_Irssi__Server_ref, file, "$");
        newXSproto("Irssi::Server::unref", XS_Irssi__Server_unref, file, "$");
        newXSproto("Irssi::Server::isnickflag", XS_Irssi__Server_isnickflag, file, "$$");
        newXSproto("Irssi::Server::ischannel", XS_Irssi__Server_ischannel, file, "$$");
        newXSproto("Irssi::Server::get_nick_flags", XS_Irssi__Server_get_nick_flags, file, "$");
        newXSproto("Irssi::Server::send_message", XS_Irssi__Server_send_message, file, "$$$$");
    XSRETURN_YES;
}

