/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Window.xs. Do not edit this file, edit Window.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Window.xs"
#include "module.h"

#include "window-activity.h"

#line 15 "Window.c"

XS(XS_Irssi_windows); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_windows)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::windows()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 11 "Window.xs"
	GSList *tmp;
#line 28 "Window.c"
#line 13 "Window.xs"
	for (tmp = windows; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::UI::Window")));
	}
#line 33 "Window.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi_active_win); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_active_win)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::active_win()");
    {
	Irssi__UI__Window	RETVAL;
#line 21 "Window.xs"
	RETVAL = active_win;
#line 50 "Window.c"
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_active_server); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_active_server)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::active_server()");
    {
	Irssi__Server	RETVAL;
#line 28 "Window.xs"
	RETVAL = active_win->active_server;
#line 69 "Window.c"
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_print); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_print)
{
    dXSARGS;
    if (items < 1 || items > 2)
	Perl_croak(aTHX_ "Usage: Irssi::print(str, level=MSGLEVEL_CLIENTNOTICE)");
    {
	char *	str = (char *)SvPV_nolen(ST(0));
	int	level;

	if (items < 2)
	    level = MSGLEVEL_CLIENTNOTICE;
	else {
	    level = (int)SvIV(ST(1));
	}
#line 37 "Window.xs"
	printtext_string(NULL, NULL, level, str);
#line 95 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_window_find_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_find_name)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::window_find_name(name)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_find_name(name);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_find_refnum); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_find_refnum)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::window_find_refnum(refnum)");
    {
	int	refnum = (int)SvIV(ST(0));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_find_refnum(refnum);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_refnum_prev); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_refnum_prev)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::window_refnum_prev(refnum, wrap)");
    {
	int	refnum = (int)SvIV(ST(0));
	int	wrap = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = window_refnum_prev(refnum, wrap);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_refnum_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_refnum_next)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::window_refnum_next(refnum, wrap)");
    {
	int	refnum = (int)SvIV(ST(0));
	int	wrap = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = window_refnum_next(refnum, wrap);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_windows_refnum_last); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_windows_refnum_last)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::windows_refnum_last()");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = windows_refnum_last();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_find_level); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_find_level)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::window_find_level(level)");
    {
	int	level = (int)SvIV(ST(0));
	Irssi__UI__Window	RETVAL;
#line 64 "Window.xs"
	RETVAL = window_find_level(NULL, level);
#line 205 "Window.c"
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_find_item); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_find_item)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::window_find_item(name)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	Irssi__UI__Window	RETVAL;
#line 72 "Window.xs"
	RETVAL = window_find_item(NULL, name);
#line 225 "Window.c"
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_find_closest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_find_closest)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::window_find_closest(name, level)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	int	level = (int)SvIV(ST(1));
	Irssi__UI__Window	RETVAL;
#line 81 "Window.xs"
	RETVAL = window_find_closest(NULL, name, level);
#line 246 "Window.c"
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi_window_item_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_window_item_find)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::window_item_find(name)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	Irssi__Windowitem	RETVAL;
#line 89 "Window.xs"
	RETVAL = window_item_find(NULL, name);
#line 266 "Window.c"
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_print); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_print)
{
    dXSARGS;
    if (items < 3 || items > 4)
	Perl_croak(aTHX_ "Usage: Irssi::Server::print(server, channel, str, level=MSGLEVEL_CLIENTNOTICE)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	channel = (char *)SvPV_nolen(ST(1));
	char *	str = (char *)SvPV_nolen(ST(2));
	int	level;

	if (items < 4)
	    level = MSGLEVEL_CLIENTNOTICE;
	else {
	    level = (int)SvIV(ST(3));
	}
#line 105 "Window.xs"
	printtext_string(server, channel, level, str);
#line 294 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Server_window_item_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_window_item_find)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Server::window_item_find(server, name)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	Irssi__Windowitem	RETVAL;

	RETVAL = window_item_find(server, name);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_window_find_item); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_window_find_item)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Server::window_find_item(server, name)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_find_item(server, name);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_window_find_level); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_window_find_level)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Server::window_find_level(server, level)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	int	level = (int)SvIV(ST(1));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_find_level(server, level);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Server_window_find_closest); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Server_window_find_closest)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::Server::window_find_closest(server, name, level)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	int	level = (int)SvIV(ST(2));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_find_closest(server, name, level);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__UI__Window_items); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_items)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::items(window)");
    SP -= items;
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
#line 137 "Window.xs"
	GSList *tmp;
#line 392 "Window.c"
#line 139 "Window.xs"
	for (tmp = window->items; tmp != NULL; tmp = tmp->next) {
                CHANNEL_REC *rec = tmp->data;

		XPUSHs(sv_2mortal(iobject_bless(rec)));
	}
#line 399 "Window.c"
	PUTBACK;
	return;
    }
}


XS(XS_Irssi__UI__Window_print); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_print)
{
    dXSARGS;
    if (items < 2 || items > 3)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::print(window, str, level=MSGLEVEL_CLIENTNOTICE)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	char *	str = (char *)SvPV_nolen(ST(1));
	int	level;

	if (items < 3)
	    level = MSGLEVEL_CLIENTNOTICE;
	else {
	    level = (int)SvIV(ST(2));
	}
#line 151 "Window.xs"
	printtext_string_window(window, level, str);
#line 424 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_command); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_command)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::command(window, cmd)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
#line 158 "Window.xs"
	WINDOW_REC *old;
#line 441 "Window.c"
#line 160 "Window.xs"
	old = active_win;
	active_win = window;
	perl_command(cmd, window->active_server, window->active);
	if (active_win == window &&
	    g_slist_find(windows, old) != NULL)
        	active_win = old;
#line 449 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_item_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_add)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::item_add(window, item, automatic)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__Windowitem	item = irssi_ref_object(ST(1));
	int	automatic = (int)SvIV(ST(2));

	window_item_add(window, item, automatic);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_item_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_remove)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::item_remove(item)");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));

	window_item_remove(item);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_item_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_destroy)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::item_destroy(item)");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));

	window_item_destroy(item);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_item_prev); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_prev)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::item_prev(window)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));

	window_item_prev(window);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_item_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_next)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::item_next(window)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));

	window_item_next(window);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_destroy)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::destroy(window)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));

	window_destroy(window);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_set_active); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_set_active)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::set_active(window)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));

	window_set_active(window);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_change_server); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_change_server)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::change_server(window, server)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__Server	server = irssi_ref_object(ST(1));

	window_change_server(window, server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_set_refnum); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_set_refnum)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::set_refnum(window, refnum)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	int	refnum = (int)SvIV(ST(1));

	window_set_refnum(window, refnum);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_set_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_set_name)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::set_name(window, name)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));

	window_set_name(window, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_set_history); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_set_history)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::set_history(window, name)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));

	window_set_history(window, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_set_level); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_set_level)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::set_level(window, level)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	int	level = (int)SvIV(ST(1));

	window_set_level(window, level);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_activity); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_activity)
{
    dXSARGS;
    if (items < 2 || items > 3)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::activity(window, data_level, hilight_color=NULL)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	int	data_level = (int)SvIV(ST(1));
	char *	hilight_color;

	if (items < 3)
	    hilight_color = NULL;
	else {
	    hilight_color = (char *)SvPV_nolen(ST(2));
	}

	window_activity(window, data_level, hilight_color);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_get_active_name); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_get_active_name)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::get_active_name(window)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	char *	RETVAL;
	dXSTARG;
#line 232 "Window.xs"
	RETVAL = (char *) window_get_active_name(window);
#line 677 "Window.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}


XS(XS_Irssi__UI__Window_item_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_item_find)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::item_find(window, server, name)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__Server	server = irssi_ref_object(ST(1));
	char *	name = (char *)SvPV_nolen(ST(2));
	Irssi__Windowitem	RETVAL;
#line 242 "Window.xs"
	RETVAL = window_item_find_window(window, server, name);
#line 697 "Window.c"
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Windowitem_print); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_print)
{
    dXSARGS;
    if (items < 2 || items > 3)
	Perl_croak(aTHX_ "Usage: Irssi::Windowitem::print(item, str, level=MSGLEVEL_CLIENTNOTICE)");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	int	level;
	char *	str = (char *)SvPV_nolen(ST(1));

	if (items < 3)
	    level = MSGLEVEL_CLIENTNOTICE;
	else {
	    level = (int)SvIV(ST(2));
	}
#line 256 "Window.xs"
	printtext_string(item->server, item->visible_name, level, str);
#line 724 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Windowitem_window_create); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_window_create)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Windowitem::window_create(item, automatic)");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	int	automatic = (int)SvIV(ST(1));
	Irssi__UI__Window	RETVAL;

	RETVAL = window_create(item, automatic);
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Windowitem_window); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_window)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Windowitem::window(item)");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	Irssi__UI__Window	RETVAL;
#line 267 "Window.xs"
	RETVAL = window_item_window(item);
#line 761 "Window.c"
	ST(0) = plain_bless(RETVAL, "Irssi::UI::Window");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__Windowitem_change_server); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_change_server)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Windowitem::change_server(item, server)");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	Irssi__Server	server = irssi_ref_object(ST(1));

	window_item_change_server(item, server);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Windowitem_is_active); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_is_active)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Windowitem::is_active(item)");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	int	RETVAL;
	dXSTARG;

	RETVAL = window_item_is_active(item);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi__Windowitem_set_active); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_set_active)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Windowitem::set_active(item)");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
#line 284 "Window.xs"
	window_item_set_active(window_item_window(item), item);
#line 814 "Window.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__Windowitem_activity); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Windowitem_activity)
{
    dXSARGS;
    if (items < 2 || items > 3)
	Perl_croak(aTHX_ "Usage: Irssi::Windowitem::activity(item, data_level, hilight_color=NULL)");
    {
	Irssi__Windowitem	item = irssi_ref_object(ST(0));
	int	data_level = (int)SvIV(ST(1));
	char *	hilight_color;

	if (items < 3)
	    hilight_color = NULL;
	else {
	    hilight_color = (char *)SvPV_nolen(ST(2));
	}

	window_item_activity(item, data_level, hilight_color);
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__UI__Window); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__UI__Window)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::windows", XS_Irssi_windows, file, "");
        newXSproto("Irssi::active_win", XS_Irssi_active_win, file, "");
        newXSproto("Irssi::active_server", XS_Irssi_active_server, file, "");
        newXSproto("Irssi::print", XS_Irssi_print, file, "$;$");
        newXSproto("Irssi::window_find_name", XS_Irssi_window_find_name, file, "$");
        newXSproto("Irssi::window_find_refnum", XS_Irssi_window_find_refnum, file, "$");
        newXSproto("Irssi::window_refnum_prev", XS_Irssi_window_refnum_prev, file, "$$");
        newXSproto("Irssi::window_refnum_next", XS_Irssi_window_refnum_next, file, "$$");
        newXSproto("Irssi::windows_refnum_last", XS_Irssi_windows_refnum_last, file, "");
        newXSproto("Irssi::window_find_level", XS_Irssi_window_find_level, file, "$");
        newXSproto("Irssi::window_find_item", XS_Irssi_window_find_item, file, "$");
        newXSproto("Irssi::window_find_closest", XS_Irssi_window_find_closest, file, "$$");
        newXSproto("Irssi::window_item_find", XS_Irssi_window_item_find, file, "$");
        newXSproto("Irssi::Server::print", XS_Irssi__Server_print, file, "$$$;$");
        newXSproto("Irssi::Server::window_item_find", XS_Irssi__Server_window_item_find, file, "$$");
        newXSproto("Irssi::Server::window_find_item", XS_Irssi__Server_window_find_item, file, "$$");
        newXSproto("Irssi::Server::window_find_level", XS_Irssi__Server_window_find_level, file, "$$");
        newXSproto("Irssi::Server::window_find_closest", XS_Irssi__Server_window_find_closest, file, "$$$");
        newXSproto("Irssi::UI::Window::items", XS_Irssi__UI__Window_items, file, "$");
        newXSproto("Irssi::UI::Window::print", XS_Irssi__UI__Window_print, file, "$$;$");
        newXSproto("Irssi::UI::Window::command", XS_Irssi__UI__Window_command, file, "$$");
        newXSproto("Irssi::UI::Window::item_add", XS_Irssi__UI__Window_item_add, file, "$$$");
        newXSproto("Irssi::UI::Window::item_remove", XS_Irssi__UI__Window_item_remove, file, "$");
        newXSproto("Irssi::UI::Window::item_destroy", XS_Irssi__UI__Window_item_destroy, file, "$");
        newXSproto("Irssi::UI::Window::item_prev", XS_Irssi__UI__Window_item_prev, file, "$");
        newXSproto("Irssi::UI::Window::item_next", XS_Irssi__UI__Window_item_next, file, "$");
        newXSproto("Irssi::UI::Window::destroy", XS_Irssi__UI__Window_destroy, file, "$");
        newXSproto("Irssi::UI::Window::set_active", XS_Irssi__UI__Window_set_active, file, "$");
        newXSproto("Irssi::UI::Window::change_server", XS_Irssi__UI__Window_change_server, file, "$$");
        newXSproto("Irssi::UI::Window::set_refnum", XS_Irssi__UI__Window_set_refnum, file, "$$");
        newXSproto("Irssi::UI::Window::set_name", XS_Irssi__UI__Window_set_name, file, "$$");
        newXSproto("Irssi::UI::Window::set_history", XS_Irssi__UI__Window_set_history, file, "$$");
        newXSproto("Irssi::UI::Window::set_level", XS_Irssi__UI__Window_set_level, file, "$$");
        newXSproto("Irssi::UI::Window::activity", XS_Irssi__UI__Window_activity, file, "$$;$");
        newXSproto("Irssi::UI::Window::get_active_name", XS_Irssi__UI__Window_get_active_name, file, "$");
        newXSproto("Irssi::UI::Window::item_find", XS_Irssi__UI__Window_item_find, file, "$$$");
        newXSproto("Irssi::Windowitem::print", XS_Irssi__Windowitem_print, file, "$$;$");
        newXSproto("Irssi::Windowitem::window_create", XS_Irssi__Windowitem_window_create, file, "$$");
        newXSproto("Irssi::Windowitem::window", XS_Irssi__Windowitem_window, file, "$");
        newXSproto("Irssi::Windowitem::change_server", XS_Irssi__Windowitem_change_server, file, "$$");
        newXSproto("Irssi::Windowitem::is_active", XS_Irssi__Windowitem_is_active, file, "$");
        newXSproto("Irssi::Windowitem::set_active", XS_Irssi__Windowitem_set_active, file, "$");
        newXSproto("Irssi::Windowitem::activity", XS_Irssi__Windowitem_activity, file, "$$;$");
    XSRETURN_YES;
}

