/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Notifylist.xs. Do not edit this file, edit Notifylist.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Notifylist.xs"
#include "module.h"

#line 13 "Notifylist.c"
XS(XS_Irssi__Irc_notifies); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_notifies)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::notifies()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 9 "Notifylist.xs"
	GSList *tmp;
#line 25 "Notifylist.c"
#line 11 "Notifylist.xs"
	for (tmp = notifies; tmp != NULL; tmp = tmp->next) {
		XPUSHs(sv_2mortal(plain_bless(tmp->data, "Irssi::Irc::Notifylist")));
	}
#line 30 "Notifylist.c"
	PUTBACK;
	return;
    }
}

XS(XS_Irssi__Irc_notifylist_add); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_notifylist_add)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::notifylist_add(mask, ircnets, away_check, idle_check_time)");
    {
	char *	mask = (char *)SvPV_nolen(ST(0));
	char *	ircnets = (char *)SvPV_nolen(ST(1));
	int	away_check = (int)SvIV(ST(2));
	int	idle_check_time = (int)SvIV(ST(3));
	Irssi__Irc__Notifylist	RETVAL;

	RETVAL = notifylist_add(mask, ircnets, away_check, idle_check_time);
	ST(0) = plain_bless(RETVAL, "Irssi::Irc::Notifylist");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Irssi__Irc_notifylist_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_notifylist_remove)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::notifylist_remove(mask)");
    {
	char *	mask = (char *)SvPV_nolen(ST(0));

	notifylist_remove(mask);
    }
    XSRETURN_EMPTY;
}

XS(XS_Irssi__Irc_notifylist_ison); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_notifylist_ison)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::notifylist_ison(nick, serverlist)");
    {
	char *	nick = (char *)SvPV_nolen(ST(0));
	char *	serverlist = (char *)SvPV_nolen(ST(1));
	Irssi__Irc__Server	RETVAL;

	RETVAL = notifylist_ison(nick, serverlist);
	ST(0) = iobject_bless((SERVER_REC *)RETVAL);

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Irssi__Irc_notifylist_find); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc_notifylist_find)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::notifylist_find(mask, ircnet)");
    {
	char *	mask = (char *)SvPV_nolen(ST(0));
	char *	ircnet = (char *)SvPV_nolen(ST(1));
	Irssi__Irc__Notifylist	RETVAL;

	RETVAL = notifylist_find(mask, ircnet);
	ST(0) = plain_bless(RETVAL, "Irssi::Irc::Notifylist");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

XS(XS_Irssi__Irc__Server_notifylist_ison_server); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_notifylist_ison_server)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::notifylist_ison_server(server, nick)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	nick = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = notifylist_ison_server(server, nick);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_Irssi__Irc__Notifylist_ircnets_match); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Notifylist_ircnets_match)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Notifylist::ircnets_match(rec, ircnet)");
    {
	Irssi__Irc__Notifylist	rec = irssi_ref_object(ST(0));
	char *	ircnet = (char *)SvPV_nolen(ST(1));
	int	RETVAL;
	dXSTARG;

	RETVAL = notifylist_ircnets_match(rec, ircnet);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Irc__Notifylist); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Irc__Notifylist)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::Irc::notifies", XS_Irssi__Irc_notifies, file, "");
        newXSproto("Irssi::Irc::notifylist_add", XS_Irssi__Irc_notifylist_add, file, "$$$$");
        newXSproto("Irssi::Irc::notifylist_remove", XS_Irssi__Irc_notifylist_remove, file, "$");
        newXSproto("Irssi::Irc::notifylist_ison", XS_Irssi__Irc_notifylist_ison, file, "$$");
        newXSproto("Irssi::Irc::notifylist_find", XS_Irssi__Irc_notifylist_find, file, "$$");
        newXSproto("Irssi::Irc::Server::notifylist_ison_server", XS_Irssi__Irc__Server_notifylist_ison_server, file, "$$");
        newXSproto("Irssi::Irc::Notifylist::ircnets_match", XS_Irssi__Irc__Notifylist_ircnets_match, file, "$$");
    XSRETURN_YES;
}

