/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Server.xs. Do not edit this file, edit Server.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Server.xs"
#include "module.h"

static GSList *register_hash2list(HV *hv)
{
	HE *he;
	GSList *list;

	if (hv == NULL)
		return NULL;

	list = NULL;
	hv_iterinit(hv);
	while ((he = hv_iternext(hv)) != NULL) {
		I32 len;
		char *key = hv_iterkey(he, &len);
		int value = (int)SvIV(HeVAL(he));

		list = g_slist_append(list, g_strdup(key));
		list = g_slist_append(list, GINT_TO_POINTER(value));
	}
	return list;
}

static GSList *event_hash2list(HV *hv)
{
	HE *he;
	GSList *list;

	if (hv == NULL)
		return NULL;

	list = NULL;
	hv_iterinit(hv);
	while ((he = hv_iternext(hv)) != NULL) {
		I32 len;
		char *key = hv_iterkey(he, &len);
		char *value = SvPV(HeVAL(he), PL_na);

		list = g_slist_append(list, g_strdup(key));
		list = g_slist_append(list, g_strdup(value));
	}
	return list;
}

#line 55 "Server.c"
XS(XS_Irssi__Irc__Server_get_channels); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_get_channels)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::get_channels(server)");
    SP -= items;
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
#line 52 "Server.xs"
	char *ret;
#line 67 "Server.c"
#line 54 "Server.xs"
	ret = irc_server_get_channels(server);
	XPUSHs(sv_2mortal(new_pv(ret)));
	g_free(ret);
#line 72 "Server.c"
	PUTBACK;
	return;
    }
}

XS(XS_Irssi__Irc__Server_send_raw); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_send_raw)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::send_raw(server, cmd)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
#line 63 "Server.xs"
	irc_send_cmd(server, cmd);
#line 89 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Irssi__Irc__Server_send_raw_now); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_send_raw_now)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::send_raw_now(server, cmd)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
#line 70 "Server.xs"
	irc_send_cmd_now(server, cmd);
#line 105 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Irssi__Irc__Server_send_raw_first); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_send_raw_first)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::send_raw_first(server, cmd)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
#line 77 "Server.xs"
	irc_send_cmd_first(server, cmd);
#line 121 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Irssi__Irc__Server_send_raw_split); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_send_raw_split)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::send_raw_split(server, cmd, nickarg, max_nicks)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	cmd = (char *)SvPV_nolen(ST(1));
	int	nickarg = (int)SvIV(ST(2));
	int	max_nicks = (int)SvIV(ST(3));
#line 86 "Server.xs"
	irc_send_cmd_split(server, cmd, nickarg, max_nicks);
#line 139 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Irssi__Irc__Server_redirect_register); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_redirect_register)
{
    dXSARGS;
    if (items != 6)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::redirect_register(command, remote, timeout, start, stop, opt)");
    {
	char *	command = (char *)SvPV_nolen(ST(0));
	int	remote = (int)SvIV(ST(1));
	int	timeout = (int)SvIV(ST(2));
	SV *	start = ST(3);
	SV *	stop = ST(4);
	SV *	opt = ST(5);
#line 99 "Server.xs"
	server_redirect_register_list(command, remote, timeout, 
				      register_hash2list(hvref(start)),
				      register_hash2list(hvref(stop)),
				      register_hash2list(hvref(opt)));
#line 162 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Irssi__Irc__Server_redirect_event); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_redirect_event)
{
    dXSARGS;
    if (items != 7)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::redirect_event(server, command, count, arg, remote, failure_signal, signals)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	command = (char *)SvPV_nolen(ST(1));
	int	count = (int)SvIV(ST(2));
	char *	arg = (char *)SvPV_nolen(ST(3));
	int	remote = (int)SvIV(ST(4));
	char *	failure_signal = (char *)SvPV_nolen(ST(5));
	SV *	signals = ST(6);
#line 114 "Server.xs"
	server_redirect_event_list(server, command, count, *arg == '\0' ? NULL : arg, remote,
				   *failure_signal == '\0' ? NULL : failure_signal,
				   event_hash2list(hvref(signals)));
#line 185 "Server.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_Irssi__Irc__Server_redirect_get_signal); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_redirect_get_signal)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::redirect_get_signal(server, event, args)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	event = (char *)SvPV_nolen(ST(1));
	char *	args = (char *)SvPV_nolen(ST(2));
	char *	RETVAL;
	dXSTARG;
#line 124 "Server.xs"
	RETVAL = (char *) server_redirect_get_signal(server, event, args);
#line 204 "Server.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_Irssi__Irc__Server_redirect_peek_signal); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_redirect_peek_signal)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::redirect_peek_signal(server, event, args)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	event = (char *)SvPV_nolen(ST(1));
	char *	args = (char *)SvPV_nolen(ST(2));
#line 134 "Server.xs"
	int redirection;
#line 222 "Server.c"
	char *	RETVAL;
	dXSTARG;
#line 136 "Server.xs"
	RETVAL = (char *) server_redirect_peek_signal(server, event, args, &redirection);
#line 227 "Server.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

XS(XS_Irssi__Irc__Server_isupport); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__Irc__Server_isupport)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::Irc::Server::isupport(server, name)");
    {
	Irssi__Irc__Server	server = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	char *	RETVAL;
	dXSTARG;
#line 145 "Server.xs"
	RETVAL = (char *) g_hash_table_lookup(server->isupport, name);
#line 246 "Server.c"
	sv_setpv(TARG, RETVAL); XSprePUSH; PUSHTARG;
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__Irc__Server); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__Irc__Server)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::Irc::Server::get_channels", XS_Irssi__Irc__Server_get_channels, file, "$");
        newXSproto("Irssi::Irc::Server::send_raw", XS_Irssi__Irc__Server_send_raw, file, "$$");
        newXSproto("Irssi::Irc::Server::send_raw_now", XS_Irssi__Irc__Server_send_raw_now, file, "$$");
        newXSproto("Irssi::Irc::Server::send_raw_first", XS_Irssi__Irc__Server_send_raw_first, file, "$$");
        newXSproto("Irssi::Irc::Server::send_raw_split", XS_Irssi__Irc__Server_send_raw_split, file, "$$$$");
        newXSproto("Irssi::Irc::Server::redirect_register", XS_Irssi__Irc__Server_redirect_register, file, "$$$$$$");
        newXSproto("Irssi::Irc::Server::redirect_event", XS_Irssi__Irc__Server_redirect_event, file, "$$$$$$$");
        newXSproto("Irssi::Irc::Server::redirect_get_signal", XS_Irssi__Irc__Server_redirect_get_signal, file, "$$$");
        newXSproto("Irssi::Irc::Server::redirect_peek_signal", XS_Irssi__Irc__Server_redirect_peek_signal, file, "$$$");
        newXSproto("Irssi::Irc::Server::isupport", XS_Irssi__Irc__Server_isupport, file, "$$");
    XSRETURN_YES;
}

