/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of TextBufferView.xs. Do not edit this file, edit TextBufferView.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "TextBufferView.xs"
#include "module.h"

#line 13 "TextBufferView.c"

XS(XS_Irssi__TextUI__TextBuffer_view_create); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBuffer_view_create)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBuffer::view_create(buffer, width, height, scroll, utf8)");
    {
	Irssi__TextUI__TextBuffer	buffer = irssi_ref_object(ST(0));
	int	width = (int)SvIV(ST(1));
	int	height = (int)SvIV(ST(2));
	int	scroll = (int)SvIV(ST(3));
	int	utf8 = (int)SvIV(ST(4));
	Irssi__TextUI__TextBufferView	RETVAL;

	RETVAL = textbuffer_view_create(buffer, width, height, scroll, utf8);
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::TextBufferView");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__TextBufferView_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_destroy)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::destroy(view)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));

	textbuffer_view_destroy(view);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_set_default_indent); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_set_default_indent)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::set_default_indent(view, default_indent, longword_noindent)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	int	default_indent = (int)SvIV(ST(1));
	int	longword_noindent = (int)SvIV(ST(2));
#line 28 "TextBufferView.xs"
	textbuffer_view_set_default_indent(view, default_indent, longword_noindent, NULL);
#line 65 "TextBufferView.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_set_scroll); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_set_scroll)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::set_scroll(view, scroll)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	int	scroll = (int)SvIV(ST(1));

	textbuffer_view_set_scroll(view, scroll);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_resize); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_resize)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::resize(view, width, height)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	int	width = (int)SvIV(ST(1));
	int	height = (int)SvIV(ST(2));

	textbuffer_view_resize(view, width, height);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_clear); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_clear)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::clear(view)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));

	textbuffer_view_clear(view);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_get_lines); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_get_lines)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::get_lines(view)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	RETVAL;

	RETVAL = textbuffer_view_get_lines(view);
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__TextBufferView_scroll); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_scroll)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::scroll(view, lines)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	int	lines = (int)SvIV(ST(1));

	textbuffer_view_scroll(view, lines);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_scroll_line); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_scroll_line)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::scroll_line(view, line)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	line = irssi_ref_object(ST(1));

	textbuffer_view_scroll_line(view, line);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_get_line_cache); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_get_line_cache)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::get_line_cache(view, line)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	line = irssi_ref_object(ST(1));
	Irssi__TextUI__LineCache	RETVAL;

	RETVAL = textbuffer_view_get_line_cache(view, line);
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::LineCache");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__TextBufferView_insert_line); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_insert_line)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::insert_line(view, line)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	line = irssi_ref_object(ST(1));

	textbuffer_view_insert_line(view, line);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_remove_line); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_remove_line)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::remove_line(view, line)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	line = irssi_ref_object(ST(1));

	textbuffer_view_remove_line(view, line);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_remove_all_lines); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_remove_all_lines)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::remove_all_lines(view)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));

	textbuffer_view_remove_all_lines(view);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_set_bookmark); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_set_bookmark)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::set_bookmark(view, name, line)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	Irssi__TextUI__Line	line = irssi_ref_object(ST(2));

	textbuffer_view_set_bookmark(view, name, line);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_set_bookmark_bottom); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_set_bookmark_bottom)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::set_bookmark_bottom(view, name)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));

	textbuffer_view_set_bookmark_bottom(view, name);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBufferView_get_bookmark); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_get_bookmark)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::get_bookmark(view, name)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));
	char *	name = (char *)SvPV_nolen(ST(1));
	Irssi__TextUI__Line	RETVAL;

	RETVAL = textbuffer_view_get_bookmark(view, name);
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__TextBufferView_redraw); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBufferView_redraw)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBufferView::redraw(view)");
    {
	Irssi__TextUI__TextBufferView	view = irssi_ref_object(ST(0));

	textbuffer_view_redraw(view);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_view); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_view)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::view(window)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__TextUI__TextBufferView	RETVAL;
#line 106 "TextBufferView.xs"
	RETVAL = WINDOW_GUI(window)->view;
#line 316 "TextBufferView.c"
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::TextBufferView");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__TextUI__TextBufferView); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__TextUI__TextBufferView)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::TextUI::TextBuffer::view_create", XS_Irssi__TextUI__TextBuffer_view_create, file, "$$$$$");
        newXSproto("Irssi::TextUI::TextBufferView::destroy", XS_Irssi__TextUI__TextBufferView_destroy, file, "$");
        newXSproto("Irssi::TextUI::TextBufferView::set_default_indent", XS_Irssi__TextUI__TextBufferView_set_default_indent, file, "$$$");
        newXSproto("Irssi::TextUI::TextBufferView::set_scroll", XS_Irssi__TextUI__TextBufferView_set_scroll, file, "$$");
        newXSproto("Irssi::TextUI::TextBufferView::resize", XS_Irssi__TextUI__TextBufferView_resize, file, "$$$");
        newXSproto("Irssi::TextUI::TextBufferView::clear", XS_Irssi__TextUI__TextBufferView_clear, file, "$");
        newXSproto("Irssi::TextUI::TextBufferView::get_lines", XS_Irssi__TextUI__TextBufferView_get_lines, file, "$");
        newXSproto("Irssi::TextUI::TextBufferView::scroll", XS_Irssi__TextUI__TextBufferView_scroll, file, "$$");
        newXSproto("Irssi::TextUI::TextBufferView::scroll_line", XS_Irssi__TextUI__TextBufferView_scroll_line, file, "$$");
        newXSproto("Irssi::TextUI::TextBufferView::get_line_cache", XS_Irssi__TextUI__TextBufferView_get_line_cache, file, "$$");
        newXSproto("Irssi::TextUI::TextBufferView::insert_line", XS_Irssi__TextUI__TextBufferView_insert_line, file, "$$");
        newXSproto("Irssi::TextUI::TextBufferView::remove_line", XS_Irssi__TextUI__TextBufferView_remove_line, file, "$$");
        newXSproto("Irssi::TextUI::TextBufferView::remove_all_lines", XS_Irssi__TextUI__TextBufferView_remove_all_lines, file, "$");
        newXSproto("Irssi::TextUI::TextBufferView::set_bookmark", XS_Irssi__TextUI__TextBufferView_set_bookmark, file, "$$$");
        newXSproto("Irssi::TextUI::TextBufferView::set_bookmark_bottom", XS_Irssi__TextUI__TextBufferView_set_bookmark_bottom, file, "$$");
        newXSproto("Irssi::TextUI::TextBufferView::get_bookmark", XS_Irssi__TextUI__TextBufferView_get_bookmark, file, "$$");
        newXSproto("Irssi::TextUI::TextBufferView::redraw", XS_Irssi__TextUI__TextBufferView_redraw, file, "$");
        newXSproto("Irssi::UI::Window::view", XS_Irssi__UI__Window_view, file, "$");
    XSRETURN_YES;
}

