/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of TextBuffer.xs. Do not edit this file, edit TextBuffer.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "TextBuffer.xs"
#include "module.h"

#line 13 "TextBuffer.c"

XS(XS_Irssi_textbuffer_create); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_textbuffer_create)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::textbuffer_create()");
    {
	Irssi__TextUI__TextBuffer	RETVAL;

	RETVAL = textbuffer_create();
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::TextBuffer");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__TextBuffer_destroy); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBuffer_destroy)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBuffer::destroy(buffer)");
    {
	Irssi__TextUI__TextBuffer	buffer = irssi_ref_object(ST(0));

	textbuffer_destroy(buffer);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBuffer_append); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBuffer_append)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBuffer::append(buffer, data, len, info)");
    {
	Irssi__TextUI__TextBuffer	buffer = irssi_ref_object(ST(0));
	char *	data = (char *)SvPV_nolen(ST(1));
	int	len = (int)SvIV(ST(2));
	Irssi__TextUI__LineInfo	info = irssi_ref_object(ST(3));
	Irssi__TextUI__Line	RETVAL;

	RETVAL = textbuffer_append(buffer, data, len, info);
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__TextBuffer_insert); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBuffer_insert)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBuffer::insert(buffer, insert_after, data, len, info)");
    {
	Irssi__TextUI__TextBuffer	buffer = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	insert_after = irssi_ref_object(ST(1));
	char *	data = (char *)SvPV_nolen(ST(2));
	int	len = (int)SvIV(ST(3));
	Irssi__TextUI__LineInfo	info = irssi_ref_object(ST(4));
	Irssi__TextUI__Line	RETVAL;

	RETVAL = textbuffer_insert(buffer, insert_after, data, len, info);
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__TextBuffer_remove); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBuffer_remove)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBuffer::remove(buffer, line)");
    {
	Irssi__TextUI__TextBuffer	buffer = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	line = irssi_ref_object(ST(1));

	textbuffer_remove(buffer, line);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__TextBuffer_remove_all_lines); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__TextBuffer_remove_all_lines)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::TextBuffer::remove_all_lines(buffer)");
    {
	Irssi__TextUI__TextBuffer	buffer = irssi_ref_object(ST(0));

	textbuffer_remove_all_lines(buffer);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__Line_prev); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__Line_prev)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::Line::prev(line)");
    {
	Irssi__TextUI__Line	line = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	RETVAL;
#line 49 "TextBuffer.xs"
	RETVAL = line->prev;
#line 135 "TextBuffer.c"
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__Line_next); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__Line_next)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::Line::next(line)");
    {
	Irssi__TextUI__Line	line = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	RETVAL;
#line 57 "TextBuffer.xs"
	RETVAL = line->next;
#line 155 "TextBuffer.c"
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__TextUI__Line_ref); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__Line_ref)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::Line::ref(line)");
    {
	Irssi__TextUI__Line	line = irssi_ref_object(ST(0));

	textbuffer_line_ref(line);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__Line_unref); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__Line_unref)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::Line::unref(line, buffer)");
    {
	Irssi__TextUI__Line	line = irssi_ref_object(ST(0));
	Irssi__TextUI__TextBuffer	buffer = irssi_ref_object(ST(1));
#line 70 "TextBuffer.xs"
	textbuffer_line_unref(buffer, line);
#line 190 "TextBuffer.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI__Line_get_text); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI__Line_get_text)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::Line::get_text(line, coloring)");
    SP -= items;
    {
	Irssi__TextUI__Line	line = irssi_ref_object(ST(0));
	int	coloring = (int)SvIV(ST(1));
#line 77 "TextBuffer.xs"
	GString *str;
	SV *result;
#line 209 "TextBuffer.c"
#line 80 "TextBuffer.xs"
	str = g_string_new(NULL);
	textbuffer_line2text(line, coloring, str);
	result = new_pv(str->str);
	XPUSHs(sv_2mortal(result));
	g_string_free(str, TRUE);
#line 216 "TextBuffer.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__TextUI__TextBuffer); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__TextUI__TextBuffer)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::textbuffer_create", XS_Irssi_textbuffer_create, file, "");
        newXSproto("Irssi::TextUI::TextBuffer::destroy", XS_Irssi__TextUI__TextBuffer_destroy, file, "$");
        newXSproto("Irssi::TextUI::TextBuffer::append", XS_Irssi__TextUI__TextBuffer_append, file, "$$$$");
        newXSproto("Irssi::TextUI::TextBuffer::insert", XS_Irssi__TextUI__TextBuffer_insert, file, "$$$$$");
        newXSproto("Irssi::TextUI::TextBuffer::remove", XS_Irssi__TextUI__TextBuffer_remove, file, "$$");
        newXSproto("Irssi::TextUI::TextBuffer::remove_all_lines", XS_Irssi__TextUI__TextBuffer_remove_all_lines, file, "$");
        newXSproto("Irssi::TextUI::Line::prev", XS_Irssi__TextUI__Line_prev, file, "$");
        newXSproto("Irssi::TextUI::Line::next", XS_Irssi__TextUI__Line_next, file, "$");
        newXSproto("Irssi::TextUI::Line::ref", XS_Irssi__TextUI__Line_ref, file, "$");
        newXSproto("Irssi::TextUI::Line::unref", XS_Irssi__TextUI__Line_unref, file, "$$");
        newXSproto("Irssi::TextUI::Line::get_text", XS_Irssi__TextUI__Line_get_text, file, "$$");
    XSRETURN_YES;
}

