/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of TextUI.xs. Do not edit this file, edit TextUI.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "TextUI.xs"
#include "module.h"

void perl_statusbar_init(void);
void perl_statusbar_deinit(void);

static int initialized = FALSE;

static void perl_main_window_fill_hash(HV *hv, MAIN_WINDOW_REC *window)
{
	hv_store(hv, "active", 6, plain_bless(window->active, "Irssi::UI::Window"), 0);

	hv_store(hv, "first_line", 10, newSViv(window->first_line), 0);
	hv_store(hv, "last_line", 9, newSViv(window->last_line), 0);
	hv_store(hv, "width", 5, newSViv(window->width), 0);
	hv_store(hv, "height", 6, newSViv(window->height), 0);

	hv_store(hv, "statusbar_lines", 15, newSViv(window->statusbar_lines), 0);
}

static void perl_text_buffer_fill_hash(HV *hv, TEXT_BUFFER_REC *buffer)
{
	hv_store(hv, "first_line", 10, plain_bless(buffer->first_line, "Irssi::TextUI::Line"), 0);
	hv_store(hv, "lines_count", 11, newSViv(buffer->lines_count), 0);
	hv_store(hv, "cur_line", 8, plain_bless(buffer->cur_line, "Irssi::TextUI::Line"), 0);
	hv_store(hv, "last_eol", 8, newSViv(buffer->last_eol), 0);
}

static void perl_text_buffer_view_fill_hash(HV *hv, TEXT_BUFFER_VIEW_REC *view)
{
	hv_store(hv, "buffer", 6, plain_bless(view->buffer, "Irssi::TextUI::TextBuffer"), 0);
	hv_store(hv, "width", 5, newSViv(view->width), 0);
	hv_store(hv, "height", 6, newSViv(view->height), 0);

	hv_store(hv, "default_indent", 14, newSViv(view->default_indent), 0);
	hv_store(hv, "longword_noindent", 17, newSViv(view->longword_noindent), 0);
	hv_store(hv, "scroll", 6, newSViv(view->scroll), 0);

	hv_store(hv, "ypos", 4, newSViv(view->ypos), 0);

	hv_store(hv, "startline", 9, plain_bless(view->startline, "Irssi::TextUI::Line"), 0);
	hv_store(hv, "subline", 7, newSViv(view->subline), 0);

	hv_store(hv, "bottom_startline", 16, plain_bless(view->bottom_startline, "Irssi::TextUI::Line"), 0);
	hv_store(hv, "bottom_subline", 14, newSViv(view->bottom_subline), 0);

	hv_store(hv, "empty_linecount", 15, newSViv(view->empty_linecount), 0);
	hv_store(hv, "bottom", 6, newSViv(view->bottom), 0);
}

static void perl_line_fill_hash(HV *hv, LINE_REC *line)
{
	hv_store(hv, "refcount", 8, newSViv(line->refcount), 0);
	hv_store(hv, "info", 4, plain_bless(&line->info, "Irssi::TextUI::LineInfo"), 0);
}

static void perl_line_cache_fill_hash(HV *hv, LINE_CACHE_REC *cache)
{
	hv_store(hv, "last_access", 11, newSViv(cache->last_access), 0);
	hv_store(hv, "count", 5, newSViv(cache->count), 0);
	/*LINE_CACHE_SUB_REC lines[1];*/
}

static void perl_line_info_fill_hash(HV *hv, LINE_INFO_REC *info)
{
	hv_store(hv, "level", 5, newSViv(info->level), 0);
	hv_store(hv, "time", 4, newSViv(info->time), 0);
}

static void perl_statusbar_item_fill_hash(HV *hv, SBAR_ITEM_REC *item)
{
	hv_store(hv, "min_size", 8, newSViv(item->min_size), 0);
	hv_store(hv, "max_size", 8, newSViv(item->max_size), 0);
	hv_store(hv, "xpos", 4, newSViv(item->xpos), 0);
	hv_store(hv, "size", 4, newSViv(item->size), 0);
	if (item->bar->parent_window != NULL)
		hv_store(hv, "window", 6, plain_bless(item->bar->parent_window->active, "Irssi::UI::Window"), 0);
}

static PLAIN_OBJECT_INIT_REC textui_plains[] = {
	{ "Irssi::TextUI::MainWindow", (PERL_OBJECT_FUNC) perl_main_window_fill_hash },
	{ "Irssi::TextUI::TextBuffer", (PERL_OBJECT_FUNC) perl_text_buffer_fill_hash },
	{ "Irssi::TextUI::TextBufferView", (PERL_OBJECT_FUNC) perl_text_buffer_view_fill_hash },
	{ "Irssi::TextUI::Line", (PERL_OBJECT_FUNC) perl_line_fill_hash },
	{ "Irssi::TextUI::LineCache", (PERL_OBJECT_FUNC) perl_line_cache_fill_hash },
	{ "Irssi::TextUI::LineInfo", (PERL_OBJECT_FUNC) perl_line_info_fill_hash },
	{ "Irssi::TextUI::StatusbarItem", (PERL_OBJECT_FUNC) perl_statusbar_item_fill_hash },

	{ NULL, NULL }
};

#line 101 "TextUI.c"

XS(XS_Irssi__TextUI_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI_init)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::init()");
    {
#line 98 "TextUI.xs"
	if (initialized) return;
	perl_api_version_check("Irssi::TextUI");
	initialized = TRUE;

        irssi_add_plains(textui_plains);
        perl_statusbar_init();
#line 117 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__TextUI_deinit); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__TextUI_deinit)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::TextUI::deinit()");
    {
#line 108 "TextUI.xs"
	if (!initialized) return;
        perl_statusbar_deinit();
	initialized = FALSE;
#line 134 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_gui_printtext); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_gui_printtext)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: Irssi::gui_printtext(xpos, ypos, str)");
    {
	int	xpos = (int)SvIV(ST(0));
	int	ypos = (int)SvIV(ST(1));
	char *	str = (char *)SvPV_nolen(ST(2));

	gui_printtext(xpos, ypos, str);
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_gui_input_set); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_gui_input_set)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::gui_input_set(str)");
    {
	char *	str = (char *)SvPV_nolen(ST(0));
#line 124 "TextUI.xs"
	gui_entry_set_text(active_entry, str);
#line 167 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi_gui_input_get_pos); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_gui_input_get_pos)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::gui_input_get_pos()");
    {
	int	RETVAL;
	dXSTARG;
#line 129 "TextUI.xs"
	RETVAL = gui_entry_get_pos(active_entry);
#line 184 "TextUI.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Irssi_gui_input_set_pos); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi_gui_input_set_pos)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::gui_input_set_pos(pos)");
    {
	int	pos = (int)SvIV(ST(0));
#line 137 "TextUI.xs"
	gui_entry_set_pos(active_entry, pos);
#line 201 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_gui_printtext_after); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_gui_printtext_after)
{
    dXSARGS;
    if (items != 4)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::gui_printtext_after(window, prev, level, str)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	prev = irssi_ref_object(ST(1));
	int	level = (int)SvIV(ST(2));
	char *	str = (char *)SvPV_nolen(ST(3));
#line 148 "TextUI.xs"
	TEXT_DEST_REC dest;
#line 220 "TextUI.c"
#line 150 "TextUI.xs"
	format_create_dest(&dest, NULL, NULL, level, window);
	gui_printtext_after(&dest, prev, str);
#line 224 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Window_last_line_insert); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Window_last_line_insert)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Window::last_line_insert(window)");
    {
	Irssi__UI__Window	window = irssi_ref_object(ST(0));
	Irssi__TextUI__Line	RETVAL;
#line 157 "TextUI.xs"
	RETVAL = WINDOW_GUI(window)->insert_after;
#line 241 "TextUI.c"
	ST(0) = plain_bless(RETVAL, "Irssi::TextUI::Line");

	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Irssi__UI__Server_gui_printtext_after); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Server_gui_printtext_after)
{
    dXSARGS;
    if (items != 5)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Server::gui_printtext_after(server, target, prev, level, str)");
    {
	Irssi__Server	server = irssi_ref_object(ST(0));
	char *	target = (char *)SvPV_nolen(ST(1));
	Irssi__TextUI__Line	prev = irssi_ref_object(ST(2));
	int	level = (int)SvIV(ST(3));
	char *	str = (char *)SvPV_nolen(ST(4));
#line 171 "TextUI.xs"
	TEXT_DEST_REC dest;
#line 264 "TextUI.c"
#line 173 "TextUI.xs"
	format_create_dest(&dest, server, target, level, NULL);
	gui_printtext_after(&dest, prev, str);
#line 268 "TextUI.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Server_term_refresh_freeze); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Server_term_refresh_freeze)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Server::term_refresh_freeze()");
    {

	term_refresh_freeze();
    }
    XSRETURN_EMPTY;
}


XS(XS_Irssi__UI__Server_term_refresh_thaw); /* prototype to pass -Wmissing-prototypes */
XS(XS_Irssi__UI__Server_term_refresh_thaw)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Irssi::UI::Server::term_refresh_thaw()");
    {

	term_refresh_thaw();
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Irssi__TextUI); /* prototype to pass -Wmissing-prototypes */
XS(boot_Irssi__TextUI)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Irssi::TextUI::init", XS_Irssi__TextUI_init, file, "");
        newXSproto("Irssi::TextUI::deinit", XS_Irssi__TextUI_deinit, file, "");
        newXSproto("Irssi::gui_printtext", XS_Irssi_gui_printtext, file, "$$$");
        newXSproto("Irssi::gui_input_set", XS_Irssi_gui_input_set, file, "$");
        newXSproto("Irssi::gui_input_get_pos", XS_Irssi_gui_input_get_pos, file, "");
        newXSproto("Irssi::gui_input_set_pos", XS_Irssi_gui_input_set_pos, file, "$");
        newXSproto("Irssi::UI::Window::gui_printtext_after", XS_Irssi__UI__Window_gui_printtext_after, file, "$$$$");
        newXSproto("Irssi::UI::Window::last_line_insert", XS_Irssi__UI__Window_last_line_insert, file, "$");
        newXSproto("Irssi::UI::Server::gui_printtext_after", XS_Irssi__UI__Server_gui_printtext_after, file, "$$$$$");
        newXSproto("Irssi::UI::Server::term_refresh_freeze", XS_Irssi__UI__Server_term_refresh_freeze, file, "");
        newXSproto("Irssi::UI::Server::term_refresh_thaw", XS_Irssi__UI__Server_term_refresh_thaw, file, "");

    /* Initialisation Section */

#line 177 "TextUI.xs"
	irssi_boot(TextUI__Statusbar);
	irssi_boot(TextUI__TextBuffer);
	irssi_boot(TextUI__TextBufferView);

#line 331 "TextUI.c"

    /* End of Initialisation Section */

    XSRETURN_YES;
}

